# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'FormInfo_base.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_InfoDialog(object):
    def setupUi(self, InfoDialog):
        InfoDialog.setObjectName("InfoDialog")
        InfoDialog.setWindowModality(QtCore.Qt.ApplicationModal)
        InfoDialog.resize(511, 176)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        InfoDialog.setPalette(palette)
        InfoDialog.setAutoFillBackground(False)
        InfoDialog.setSizeGripEnabled(True)
        InfoDialog.setModal(True)
        self.label = QtWidgets.QLabel(InfoDialog)
        self.label.setGeometry(QtCore.QRect(20, 20, 46, 13))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/plugins/RipartPlugin/icon.png"))
        self.label.setObjectName("label")
        self.logo = QtWidgets.QLabel(InfoDialog)
        self.logo.setGeometry(QtCore.QRect(10, 0, 121, 141))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.logo.setFont(font)
        self.logo.setText("")
        self.logo.setPixmap(QtGui.QPixmap(":/plugins/RipartPlugin/images/logo_IGN.png"))
        self.logo.setScaledContents(True)
        self.logo.setObjectName("logo")
        self.textInfo = QtWidgets.QTextBrowser(InfoDialog)
        self.textInfo.setGeometry(QtCore.QRect(150, 10, 341, 121))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(81, 81, 81))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(81, 81, 81))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        self.textInfo.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.textInfo.setFont(font)
        self.textInfo.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.textInfo.setLineWidth(0)
        self.textInfo.setObjectName("textInfo")
        self.btnOK = QtWidgets.QPushButton(InfoDialog)
        self.btnOK.setGeometry(QtCore.QRect(430, 140, 75, 23))
        self.btnOK.setObjectName("btnOK")

        self.retranslateUi(InfoDialog)
        QtCore.QMetaObject.connectSlotsByName(InfoDialog)

    def retranslateUi(self, InfoDialog):
        _translate = QtCore.QCoreApplication.translate
        InfoDialog.setWindowTitle(_translate("InfoDialog", "Espace Collaboratif IGN"))
        self.btnOK.setText(_translate("InfoDialog", "Ok"))
