# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'FormCreerRemarque_base.ui'
#
# Created: Wed Nov 08 12:02:48 2017
#      by: PyQt4 UI code generator 4.10.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_dlgCreateRem(object):
    def setupUi(self, dlgCreateRem):
        dlgCreateRem.setObjectName(_fromUtf8("dlgCreateRem"))
        dlgCreateRem.resize(432, 538)
        self.groupBoxProfil = QtGui.QGroupBox(dlgCreateRem)
        self.groupBoxProfil.setGeometry(QtCore.QRect(10, 10, 411, 481))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.groupBoxProfil.setFont(font)
        self.groupBoxProfil.setObjectName(_fromUtf8("groupBoxProfil"))
        self.tabWidget = QtGui.QTabWidget(self.groupBoxProfil)
        self.tabWidget.setGeometry(QtCore.QRect(10, 50, 391, 231))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.tabWidget.setFont(font)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tabTheme = QtGui.QWidget()
        self.tabTheme.setObjectName(_fromUtf8("tabTheme"))
        self.listWidgetThemes = QtGui.QListWidget(self.tabTheme)
        self.listWidgetThemes.setGeometry(QtCore.QRect(0, 0, 391, 201))
        self.listWidgetThemes.setObjectName(_fromUtf8("listWidgetThemes"))
        self.treeWidget = QtGui.QTreeWidget(self.tabTheme)
        self.treeWidget.setGeometry(QtCore.QRect(10, 10, 351, 171))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.treeWidget.sizePolicy().hasHeightForWidth())
        self.treeWidget.setSizePolicy(sizePolicy)
        self.treeWidget.setObjectName(_fromUtf8("treeWidget"))
        self.treeWidget.headerItem().setText(0, _fromUtf8("theme"))
        item_0 = QtGui.QTreeWidgetItem(self.treeWidget)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        item_1.setCheckState(1, QtCore.Qt.Unchecked)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item_1.setBackground(1, brush)
        item_1.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        self.tabWidget.addTab(self.tabTheme, _fromUtf8(""))
        self.tabOption = QtGui.QWidget()
        self.tabOption.setObjectName(_fromUtf8("tabOption"))
        self.verticalLayoutWidget = QtGui.QWidget(self.tabOption)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 10, 480, 121))
        self.verticalLayoutWidget.setObjectName(_fromUtf8("verticalLayoutWidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.checkBoxJoinCroquis = QtGui.QCheckBox(self.verticalLayoutWidget)
        self.checkBoxJoinCroquis.setMaximumSize(QtCore.QSize(16777215, 15))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.checkBoxJoinCroquis.setFont(font)
        self.checkBoxJoinCroquis.setChecked(True)
        self.checkBoxJoinCroquis.setObjectName(_fromUtf8("checkBoxJoinCroquis"))
        self.verticalLayout.addWidget(self.checkBoxJoinCroquis)
        self.checkBoxAttDoc = QtGui.QCheckBox(self.verticalLayoutWidget)
        self.checkBoxAttDoc.setMaximumSize(QtCore.QSize(16777215, 15))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.checkBoxAttDoc.setFont(font)
        self.checkBoxAttDoc.setObjectName(_fromUtf8("checkBoxAttDoc"))
        self.verticalLayout.addWidget(self.checkBoxAttDoc)
        self.lblDoc = QtGui.QLabel(self.verticalLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblDoc.sizePolicy().hasHeightForWidth())
        self.lblDoc.setSizePolicy(sizePolicy)
        self.lblDoc.setMaximumSize(QtCore.QSize(16777215, 10))
        font = QtGui.QFont()
        font.setItalic(True)
        self.lblDoc.setFont(font)
        self.lblDoc.setObjectName(_fromUtf8("lblDoc"))
        self.verticalLayout.addWidget(self.lblDoc)
        self.line = QtGui.QFrame(self.verticalLayoutWidget)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.verticalLayout.addWidget(self.line)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setSpacing(2)
        self.horizontalLayout.setSizeConstraint(QtGui.QLayout.SetFixedSize)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.radioBtnUnique = QtGui.QRadioButton(self.verticalLayoutWidget)
        self.radioBtnUnique.setMaximumSize(QtCore.QSize(180, 16777215))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.radioBtnUnique.setFont(font)
        self.radioBtnUnique.setChecked(True)
        self.radioBtnUnique.setObjectName(_fromUtf8("radioBtnUnique"))
        self.horizontalLayout.addWidget(self.radioBtnUnique)
        self.radioBtnMultiple = QtGui.QRadioButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.radioBtnMultiple.setFont(font)
        self.radioBtnMultiple.setObjectName(_fromUtf8("radioBtnMultiple"))
        self.horizontalLayout.addWidget(self.radioBtnMultiple)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.tabWidget.addTab(self.tabOption, _fromUtf8(""))
        self.textEditMessage = QtGui.QTextEdit(self.groupBoxProfil)
        self.textEditMessage.setGeometry(QtCore.QRect(10, 310, 391, 161))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.textEditMessage.setFont(font)
        self.textEditMessage.setObjectName(_fromUtf8("textEditMessage"))
        self.lblMessage = QtGui.QLabel(self.groupBoxProfil)
        self.lblMessage.setGeometry(QtCore.QRect(10, 290, 51, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.lblMessage.setFont(font)
        self.lblMessage.setObjectName(_fromUtf8("lblMessage"))
        self.lblProfilIcon = QtGui.QLabel(self.groupBoxProfil)
        self.lblProfilIcon.setGeometry(QtCore.QRect(370, 10, 41, 41))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.lblProfilIcon.setFont(font)
        self.lblProfilIcon.setText(_fromUtf8(""))
        self.lblProfilIcon.setObjectName(_fromUtf8("lblProfilIcon"))
        self.label = QtGui.QLabel(self.groupBoxProfil)
        self.label.setGeometry(QtCore.QRect(10, 30, 161, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.lblMessageError = QtGui.QLabel(self.groupBoxProfil)
        self.lblMessageError.setGeometry(QtCore.QRect(70, 290, 321, 16))
        self.lblMessageError.setText(_fromUtf8(""))
        self.lblMessageError.setObjectName(_fromUtf8("lblMessageError"))
        self.buttonBox = QtGui.QDialogButtonBox(dlgCreateRem)
        self.buttonBox.setGeometry(QtCore.QRect(260, 500, 156, 23))
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))

        self.retranslateUi(dlgCreateRem)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(dlgCreateRem)

    def retranslateUi(self, dlgCreateRem):
        dlgCreateRem.setWindowTitle(_translate("dlgCreateRem", "IGN RIPart : Créer un nouveau signalement", None))
        self.groupBoxProfil.setTitle(_translate("dlgCreateRem", "Profil", None))
        self.treeWidget.headerItem().setText(1, _translate("dlgCreateRem", "att", None))
        __sortingEnabled = self.treeWidget.isSortingEnabled()
        self.treeWidget.setSortingEnabled(False)
        self.treeWidget.topLevelItem(0).setText(0, _translate("dlgCreateRem", "th1", None))
        self.treeWidget.topLevelItem(0).child(0).setText(0, _translate("dlgCreateRem", "possible?", None))
        self.treeWidget.topLevelItem(0).child(1).setText(0, _translate("dlgCreateRem", "comment", None))
        self.treeWidget.topLevelItem(0).child(2).setText(0, _translate("dlgCreateRem", "liste", None))
        self.treeWidget.setSortingEnabled(__sortingEnabled)
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabTheme), _translate("dlgCreateRem", "Thèmes", None))
        self.checkBoxJoinCroquis.setText(_translate("dlgCreateRem", "Joindre un croquis", None))
        self.checkBoxAttDoc.setText(_translate("dlgCreateRem", "Joindre un document", None))
        self.lblDoc.setText(_translate("dlgCreateRem", "TextLabel", None))
        self.radioBtnUnique.setText(_translate("dlgCreateRem", "Créer une remarque unique", None))
        self.radioBtnMultiple.setText(_translate("dlgCreateRem", "Créer remarques distinctes", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabOption), _translate("dlgCreateRem", "Options", None))
        self.lblMessage.setText(_translate("dlgCreateRem", "Message", None))
        self.label.setText(_translate("dlgCreateRem", "Nouveau signalement", None))

