# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'FormChoixGroupe_base.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DialogParametrage(object):
    def setupUi(self, DialogParametrage):
        DialogParametrage.setObjectName("DialogParametrage")
        DialogParametrage.resize(345, 261)
        DialogParametrage.setStyleSheet("QDialog {background-color: rgb(255, 255, 255)}")
        self.buttonBox = QtWidgets.QDialogButtonBox(DialogParametrage)
        self.buttonBox.setEnabled(True)
        self.buttonBox.setGeometry(QtCore.QRect(70, 220, 201, 31))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Save)
        self.buttonBox.setCenterButtons(True)
        self.buttonBox.setObjectName("buttonBox")
        self.lblGroupComment = QtWidgets.QLabel(DialogParametrage)
        self.lblGroupComment.setGeometry(QtCore.QRect(10, 20, 331, 51))
        font = QtGui.QFont()
        font.setItalic(True)
        font.setUnderline(False)
        font.setStrikeOut(False)
        self.lblGroupComment.setFont(font)
        self.lblGroupComment.setAutoFillBackground(False)
        self.lblGroupComment.setWordWrap(True)
        self.lblGroupComment.setObjectName("lblGroupComment")
        self.comboBoxGroup = QtWidgets.QComboBox(DialogParametrage)
        self.comboBoxGroup.setGeometry(QtCore.QRect(10, 70, 321, 22))
        self.comboBoxGroup.setObjectName("comboBoxGroup")
        self.lblGroup = QtWidgets.QLabel(DialogParametrage)
        self.lblGroup.setGeometry(QtCore.QRect(10, 0, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.lblGroup.setFont(font)
        self.lblGroup.setObjectName("lblGroup")
        self.lblWorkZone = QtWidgets.QLabel(DialogParametrage)
        self.lblWorkZone.setGeometry(QtCore.QRect(10, 110, 121, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.lblWorkZone.setFont(font)
        self.lblWorkZone.setObjectName("lblWorkZone")
        self.lblWorkZoneComment = QtWidgets.QLabel(DialogParametrage)
        self.lblWorkZoneComment.setGeometry(QtCore.QRect(10, 130, 291, 41))
        font = QtGui.QFont()
        font.setItalic(True)
        self.lblWorkZoneComment.setFont(font)
        self.lblWorkZoneComment.setWordWrap(True)
        self.lblWorkZoneComment.setObjectName("lblWorkZoneComment")
        self.comboBoxWorkZone = QtWidgets.QComboBox(DialogParametrage)
        self.comboBoxWorkZone.setGeometry(QtCore.QRect(10, 180, 281, 22))
        self.comboBoxWorkZone.setObjectName("comboBoxWorkZone")
        self.toolButtonShapeFile = QtWidgets.QToolButton(DialogParametrage)
        self.toolButtonShapeFile.setGeometry(QtCore.QRect(300, 180, 27, 22))
        self.toolButtonShapeFile.setObjectName("toolButtonShapeFile")

        self.retranslateUi(DialogParametrage)
        QtCore.QMetaObject.connectSlotsByName(DialogParametrage)

    def retranslateUi(self, DialogParametrage):
        _translate = QtCore.QCoreApplication.translate
        DialogParametrage.setWindowTitle(_translate("DialogParametrage", "Paramètres de travail"))
        self.lblGroupComment.setText(_translate("DialogParametrage", "Choississez parmi les groupes auxquels vous appartenez celui dans lequel vous souhaitez travailler"))
        self.lblGroup.setText(_translate("DialogParametrage", "Groupe"))
        self.lblWorkZone.setText(_translate("DialogParametrage", "Zone de travail"))
        self.lblWorkZoneComment.setText(_translate("DialogParametrage", "La zone de travail sera utilisée pour télécharger les signalements ou les données de votre groupe"))
        self.toolButtonShapeFile.setText(_translate("DialogParametrage", "..."))
