# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'FormConfigurerRipart_base.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(684, 582)
        font = QtGui.QFont()
        font.setPointSize(10)
        Dialog.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/plugins/RipartPlugin/images/ign.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        Dialog.setModal(True)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(330, 530, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.formLayoutWidget = QtWidgets.QWidget(Dialog)
        self.formLayoutWidget.setGeometry(QtCore.QRect(0, 10, 671, 471))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout_2 = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout_2.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_2.setContentsMargins(0, 0, 0, 0)
        self.formLayout_2.setObjectName("formLayout_2")
        self.lblUrl = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lblUrl.setFont(font)
        self.lblUrl.setObjectName("lblUrl")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.lblUrl)
        self.lineEditUrl = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.lineEditUrl.setMinimumSize(QtCore.QSize(2, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEditUrl.setFont(font)
        self.lineEditUrl.setFrame(True)
        self.lineEditUrl.setObjectName("lineEditUrl")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEditUrl)
        self.checkBoxLogin = QtWidgets.QCheckBox(self.formLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBoxLogin.sizePolicy().hasHeightForWidth())
        self.checkBoxLogin.setSizePolicy(sizePolicy)
        self.checkBoxLogin.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.checkBoxLogin.setFont(font)
        self.checkBoxLogin.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.checkBoxLogin.setAutoFillBackground(False)
        self.checkBoxLogin.setObjectName("checkBoxLogin")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.checkBoxLogin)
        self.lineEditLogin = QtWidgets.QLineEdit(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEditLogin.setFont(font)
        self.lineEditLogin.setObjectName("lineEditLogin")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEditLogin)
        self.checkBoxPagination = QtWidgets.QCheckBox(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.checkBoxPagination.setFont(font)
        self.checkBoxPagination.setObjectName("checkBoxPagination")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.checkBoxPagination)
        self.spinBoxPagination = QtWidgets.QSpinBox(self.formLayoutWidget)
        self.spinBoxPagination.setMinimum(10)
        self.spinBoxPagination.setMaximum(2147483647)
        self.spinBoxPagination.setObjectName("spinBoxPagination")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.spinBoxPagination)
        self.checkBoxDate = QtWidgets.QCheckBox(self.formLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBoxDate.sizePolicy().hasHeightForWidth())
        self.checkBoxDate.setSizePolicy(sizePolicy)
        self.checkBoxDate.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.checkBoxDate.setFont(font)
        self.checkBoxDate.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.checkBoxDate.setAutoFillBackground(False)
        self.checkBoxDate.setObjectName("checkBoxDate")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.checkBoxDate)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.calendarWidget = QtWidgets.QCalendarWidget(self.formLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.calendarWidget.sizePolicy().hasHeightForWidth())
        self.calendarWidget.setSizePolicy(sizePolicy)
        self.calendarWidget.setMaximumSize(QtCore.QSize(270, 110))
        self.calendarWidget.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.calendarWidget.setFont(font)
        self.calendarWidget.setLocale(QtCore.QLocale(QtCore.QLocale.French, QtCore.QLocale.France))
        self.calendarWidget.setSelectedDate(QtCore.QDate(2015, 10, 21))
        self.calendarWidget.setFirstDayOfWeek(QtCore.Qt.Monday)
        self.calendarWidget.setGridVisible(False)
        self.calendarWidget.setVerticalHeaderFormat(QtWidgets.QCalendarWidget.NoVerticalHeader)
        self.calendarWidget.setObjectName("calendarWidget")
        self.horizontalLayout_2.addWidget(self.calendarWidget)
        self.spinBox = QtWidgets.QSpinBox(self.formLayoutWidget)
        self.spinBox.setMaximum(2147483647)
        self.spinBox.setObjectName("spinBox")
        self.horizontalLayout_2.addWidget(self.spinBox)
        self.label_2 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.formLayout_2.setLayout(4, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_2)
        self.checkBoxFiltre = QtWidgets.QCheckBox(self.formLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBoxFiltre.sizePolicy().hasHeightForWidth())
        self.checkBoxFiltre.setSizePolicy(sizePolicy)
        self.checkBoxFiltre.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.checkBoxFiltre.setFont(font)
        self.checkBoxFiltre.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.checkBoxFiltre.setAutoFillBackground(False)
        self.checkBoxFiltre.setObjectName("checkBoxFiltre")
        self.formLayout_2.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.checkBoxFiltre)
        self.comboBoxFiltre = QtWidgets.QComboBox(self.formLayoutWidget)
        self.comboBoxFiltre.setObjectName("comboBoxFiltre")
        self.formLayout_2.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.comboBoxFiltre)
        self.checkBoxGroup = QtWidgets.QCheckBox(self.formLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBoxGroup.sizePolicy().hasHeightForWidth())
        self.checkBoxGroup.setSizePolicy(sizePolicy)
        self.checkBoxGroup.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.checkBoxGroup.setFont(font)
        self.checkBoxGroup.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.checkBoxGroup.setAutoFillBackground(False)
        self.checkBoxGroup.setObjectName("checkBoxGroup")
        self.formLayout_2.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.checkBoxGroup)
        self.lblGroup = QtWidgets.QLabel(self.formLayoutWidget)
        self.lblGroup.setText("")
        self.lblGroup.setObjectName("lblGroup")
        self.formLayout_2.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.lblGroup)
        self.checkBoxAttributs = QtWidgets.QCheckBox(self.formLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBoxAttributs.sizePolicy().hasHeightForWidth())
        self.checkBoxAttributs.setSizePolicy(sizePolicy)
        self.checkBoxAttributs.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.checkBoxAttributs.setFont(font)
        self.checkBoxAttributs.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.checkBoxAttributs.setAutoFillBackground(False)
        self.checkBoxAttributs.setObjectName("checkBoxAttributs")
        self.formLayout_2.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.checkBoxAttributs)
        self.treeWidget = QtWidgets.QTreeWidget(self.formLayoutWidget)
        self.treeWidget.setLineWidth(100)
        self.treeWidget.setAlternatingRowColors(True)
        self.treeWidget.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.treeWidget.setColumnCount(1)
        self.treeWidget.setObjectName("treeWidget")
        self.treeWidget.headerItem().setText(0, "1")
        self.treeWidget.header().setVisible(False)
        self.formLayout_2.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.treeWidget)
        self.lblProxy = QtWidgets.QLabel(Dialog)
        self.lblProxy.setGeometry(QtCore.QRect(10, 480, 251, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lblProxy.setFont(font)
        self.lblProxy.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblProxy.setObjectName("lblProxy")
        self.lineEditProxy = QtWidgets.QLineEdit(Dialog)
        self.lineEditProxy.setGeometry(QtCore.QRect(275, 480, 395, 22))
        self.lineEditProxy.setMinimumSize(QtCore.QSize(2, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEditProxy.setFont(font)
        self.lineEditProxy.setFrame(True)
        self.lineEditProxy.setObjectName("lineEditProxy")

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.lineEditUrl, self.checkBoxLogin)
        Dialog.setTabOrder(self.checkBoxLogin, self.lineEditLogin)
        Dialog.setTabOrder(self.lineEditLogin, self.checkBoxPagination)
        Dialog.setTabOrder(self.checkBoxPagination, self.spinBoxPagination)
        Dialog.setTabOrder(self.spinBoxPagination, self.checkBoxDate)
        Dialog.setTabOrder(self.checkBoxDate, self.calendarWidget)
        Dialog.setTabOrder(self.calendarWidget, self.spinBox)
        Dialog.setTabOrder(self.spinBox, self.checkBoxFiltre)
        Dialog.setTabOrder(self.checkBoxFiltre, self.comboBoxFiltre)
        Dialog.setTabOrder(self.comboBoxFiltre, self.checkBoxGroup)
        Dialog.setTabOrder(self.checkBoxGroup, self.checkBoxAttributs)
        Dialog.setTabOrder(self.checkBoxAttributs, self.treeWidget)
        Dialog.setTabOrder(self.treeWidget, self.buttonBox)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Configuration du plugin RIPart"))
        self.lblUrl.setText(_translate("Dialog", "Adresse de connexion au service RIPart"))
        self.checkBoxLogin.setText(_translate("Dialog", "Login par défaut"))
        self.checkBoxPagination.setText(_translate("Dialog", "Pagination"))
        self.checkBoxDate.setText(_translate("Dialog", "Date d\'extraction"))
        self.label_2.setText(_translate("Dialog", "jours"))
        self.checkBoxFiltre.setText(_translate("Dialog", "Calque pour filtrage spatial"))
        self.checkBoxGroup.setText(_translate("Dialog", "Extraction pour groupe"))
        self.checkBoxAttributs.setText(_translate("Dialog", "Calques sources et champs à mettre \n"
"en attribut pour les nouveaux croquis"))
        self.lblProxy.setText(_translate("Dialog", "Proxy"))

