# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'FormConfigurerRipart_base.ui'
#
# Created: Fri Oct 23 10:02:47 2015
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(684, 515)
        font = QtGui.QFont()
        font.setPointSize(10)
        Dialog.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/RipartPlugin/images/ign.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        Dialog.setModal(True)
        self.buttonBox = QtGui.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(330, 480, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.formLayoutWidget = QtGui.QWidget(Dialog)
        self.formLayoutWidget.setGeometry(QtCore.QRect(0, 10, 671, 461))
        self.formLayoutWidget.setObjectName(_fromUtf8("formLayoutWidget"))
        self.formLayout_2 = QtGui.QFormLayout(self.formLayoutWidget)
        self.formLayout_2.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_2.setMargin(0)
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        self.lblUrl = QtGui.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lblUrl.setFont(font)
        self.lblUrl.setObjectName(_fromUtf8("lblUrl"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.lblUrl)
        self.lineEditUrl = QtGui.QLineEdit(self.formLayoutWidget)
        self.lineEditUrl.setMinimumSize(QtCore.QSize(2, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEditUrl.setFont(font)
        self.lineEditUrl.setFrame(True)
        self.lineEditUrl.setObjectName(_fromUtf8("lineEditUrl"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.FieldRole, self.lineEditUrl)
        self.checkBoxLogin = QtGui.QCheckBox(self.formLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBoxLogin.sizePolicy().hasHeightForWidth())
        self.checkBoxLogin.setSizePolicy(sizePolicy)
        self.checkBoxLogin.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.checkBoxLogin.setFont(font)
        self.checkBoxLogin.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.checkBoxLogin.setAutoFillBackground(False)
        self.checkBoxLogin.setObjectName(_fromUtf8("checkBoxLogin"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.checkBoxLogin)
        self.lineEditLogin = QtGui.QLineEdit(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEditLogin.setFont(font)
        self.lineEditLogin.setObjectName(_fromUtf8("lineEditLogin"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.FieldRole, self.lineEditLogin)
        self.checkBoxDate = QtGui.QCheckBox(self.formLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBoxDate.sizePolicy().hasHeightForWidth())
        self.checkBoxDate.setSizePolicy(sizePolicy)
        self.checkBoxDate.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.checkBoxDate.setFont(font)
        self.checkBoxDate.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.checkBoxDate.setAutoFillBackground(False)
        self.checkBoxDate.setObjectName(_fromUtf8("checkBoxDate"))
        self.formLayout_2.setWidget(4, QtGui.QFormLayout.LabelRole, self.checkBoxDate)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.calendarWidget = QtGui.QCalendarWidget(self.formLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.calendarWidget.sizePolicy().hasHeightForWidth())
        self.calendarWidget.setSizePolicy(sizePolicy)
        self.calendarWidget.setMaximumSize(QtCore.QSize(270, 110))
        self.calendarWidget.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.calendarWidget.setFont(font)
        self.calendarWidget.setLocale(QtCore.QLocale(QtCore.QLocale.French, QtCore.QLocale.France))
        self.calendarWidget.setSelectedDate(QtCore.QDate(2015, 10, 21))
        self.calendarWidget.setFirstDayOfWeek(QtCore.Qt.Monday)
        self.calendarWidget.setGridVisible(False)
        self.calendarWidget.setVerticalHeaderFormat(QtGui.QCalendarWidget.NoVerticalHeader)
        self.calendarWidget.setObjectName(_fromUtf8("calendarWidget"))
        self.horizontalLayout_2.addWidget(self.calendarWidget)
        self.spinBox = QtGui.QSpinBox(self.formLayoutWidget)
        self.spinBox.setMaximum(2147483647)
        self.spinBox.setObjectName(_fromUtf8("spinBox"))
        self.horizontalLayout_2.addWidget(self.spinBox)
        self.label_2 = QtGui.QLabel(self.formLayoutWidget)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_2.addWidget(self.label_2)
        self.formLayout_2.setLayout(4, QtGui.QFormLayout.FieldRole, self.horizontalLayout_2)
        self.checkBoxFiltre = QtGui.QCheckBox(self.formLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBoxFiltre.sizePolicy().hasHeightForWidth())
        self.checkBoxFiltre.setSizePolicy(sizePolicy)
        self.checkBoxFiltre.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.checkBoxFiltre.setFont(font)
        self.checkBoxFiltre.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.checkBoxFiltre.setAutoFillBackground(False)
        self.checkBoxFiltre.setObjectName(_fromUtf8("checkBoxFiltre"))
        self.formLayout_2.setWidget(6, QtGui.QFormLayout.LabelRole, self.checkBoxFiltre)
        self.comboBoxFiltre = QtGui.QComboBox(self.formLayoutWidget)
        self.comboBoxFiltre.setObjectName(_fromUtf8("comboBoxFiltre"))
        self.formLayout_2.setWidget(6, QtGui.QFormLayout.FieldRole, self.comboBoxFiltre)
        self.checkBoxGroup = QtGui.QCheckBox(self.formLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBoxGroup.sizePolicy().hasHeightForWidth())
        self.checkBoxGroup.setSizePolicy(sizePolicy)
        self.checkBoxGroup.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.checkBoxGroup.setFont(font)
        self.checkBoxGroup.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.checkBoxGroup.setAutoFillBackground(False)
        self.checkBoxGroup.setObjectName(_fromUtf8("checkBoxGroup"))
        self.formLayout_2.setWidget(7, QtGui.QFormLayout.LabelRole, self.checkBoxGroup)
        self.lblGroup = QtGui.QLabel(self.formLayoutWidget)
        self.lblGroup.setText(_fromUtf8(""))
        self.lblGroup.setObjectName(_fromUtf8("lblGroup"))
        self.formLayout_2.setWidget(7, QtGui.QFormLayout.FieldRole, self.lblGroup)
        self.checkBoxAttributs = QtGui.QCheckBox(self.formLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBoxAttributs.sizePolicy().hasHeightForWidth())
        self.checkBoxAttributs.setSizePolicy(sizePolicy)
        self.checkBoxAttributs.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.checkBoxAttributs.setFont(font)
        self.checkBoxAttributs.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.checkBoxAttributs.setAutoFillBackground(False)
        self.checkBoxAttributs.setObjectName(_fromUtf8("checkBoxAttributs"))
        self.formLayout_2.setWidget(8, QtGui.QFormLayout.LabelRole, self.checkBoxAttributs)
        self.treeWidget = QtGui.QTreeWidget(self.formLayoutWidget)
        self.treeWidget.setLineWidth(100)
        self.treeWidget.setAlternatingRowColors(True)
        self.treeWidget.setSelectionMode(QtGui.QAbstractItemView.MultiSelection)
        self.treeWidget.setColumnCount(1)
        self.treeWidget.setObjectName(_fromUtf8("treeWidget"))
        self.treeWidget.headerItem().setText(0, _fromUtf8("1"))
        self.treeWidget.header().setVisible(False)
        self.formLayout_2.setWidget(8, QtGui.QFormLayout.FieldRole, self.treeWidget)
        self.checkBoxPagination = QtGui.QCheckBox(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.checkBoxPagination.setFont(font)
        self.checkBoxPagination.setObjectName(_fromUtf8("checkBoxPagination"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.LabelRole, self.checkBoxPagination)
        self.spinBoxPagination = QtGui.QSpinBox(self.formLayoutWidget)
        self.spinBoxPagination.setMaximum(2147483647)
        self.spinBoxPagination.setObjectName(_fromUtf8("spinBoxPagination"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.FieldRole, self.spinBoxPagination)

        self.retranslateUi(Dialog)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), Dialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.lineEditUrl, self.checkBoxLogin)
        Dialog.setTabOrder(self.checkBoxLogin, self.lineEditLogin)
        Dialog.setTabOrder(self.lineEditLogin, self.checkBoxPagination)
        Dialog.setTabOrder(self.checkBoxPagination, self.spinBoxPagination)
        Dialog.setTabOrder(self.spinBoxPagination, self.checkBoxDate)
        Dialog.setTabOrder(self.checkBoxDate, self.calendarWidget)
        Dialog.setTabOrder(self.calendarWidget, self.spinBox)
        Dialog.setTabOrder(self.spinBox, self.checkBoxFiltre)
        Dialog.setTabOrder(self.checkBoxFiltre, self.comboBoxFiltre)
        Dialog.setTabOrder(self.comboBoxFiltre, self.checkBoxGroup)
        Dialog.setTabOrder(self.checkBoxGroup, self.checkBoxAttributs)
        Dialog.setTabOrder(self.checkBoxAttributs, self.treeWidget)
        Dialog.setTabOrder(self.treeWidget, self.buttonBox)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "Configuration du plugin RIPart", None))
        self.lblUrl.setText(_translate("Dialog", "Adresse de connexion au service RIPart", None))
        self.checkBoxLogin.setText(_translate("Dialog", "Login par défaut", None))
        self.checkBoxDate.setText(_translate("Dialog", "Date d\'extraction", None))
        self.label_2.setText(_translate("Dialog", "jours", None))
        self.checkBoxFiltre.setText(_translate("Dialog", "Calque pour filtrage spécial", None))
        self.checkBoxGroup.setText(_translate("Dialog", "Extraction pour groupe", None))
        self.checkBoxAttributs.setText(_translate("Dialog", "Calques sources et champs à mettre \n"
"en attribut pour les nouveaux croquis", None))
        self.checkBoxPagination.setText(_translate("Dialog", "Pagination", None))

