# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'FormRepondre_base.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_addResponse(object):
    def setupUi(self, addResponse):
        addResponse.setObjectName("addResponse")
        addResponse.resize(360, 521)
        icon = QtGui.QIcon.fromTheme("IGN")
        addResponse.setWindowIcon(icon)
        self.btnCancel = QtWidgets.QDialogButtonBox(addResponse)
        self.btnCancel.setGeometry(QtCore.QRect(280, 490, 75, 23))
        self.btnCancel.setOrientation(QtCore.Qt.Horizontal)
        self.btnCancel.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel)
        self.btnCancel.setCenterButtons(False)
        self.btnCancel.setObjectName("btnCancel")
        self.btnSend = QtWidgets.QPushButton(addResponse)
        self.btnSend.setGeometry(QtCore.QRect(130, 490, 141, 23))
        self.btnSend.setObjectName("btnSend")
        self.lblStatut = QtWidgets.QLabel(addResponse)
        self.lblStatut.setGeometry(QtCore.QRect(10, 10, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.lblStatut.setFont(font)
        self.lblStatut.setObjectName("lblStatut")
        self.cboxStatut = QtWidgets.QComboBox(addResponse)
        self.cboxStatut.setGeometry(QtCore.QRect(70, 10, 271, 22))
        self.cboxStatut.setObjectName("cboxStatut")
        self.lblMessage = QtWidgets.QLabel(addResponse)
        self.lblMessage.setGeometry(QtCore.QRect(10, 50, 331, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.lblMessage.setFont(font)
        self.lblMessage.setObjectName("lblMessage")
        self.textMessage = QtWidgets.QTextBrowser(addResponse)
        self.textMessage.setGeometry(QtCore.QRect(10, 70, 341, 91))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.textMessage.setFont(font)
        self.textMessage.setObjectName("textMessage")
        self.lblOldResponse = QtWidgets.QLabel(addResponse)
        self.lblOldResponse.setGeometry(QtCore.QRect(10, 180, 331, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.lblOldResponse.setFont(font)
        self.lblOldResponse.setObjectName("lblOldResponse")
        self.textOldRep = QtWidgets.QTextBrowser(addResponse)
        self.textOldRep.setGeometry(QtCore.QRect(10, 200, 341, 101))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.textOldRep.setFont(font)
        self.textOldRep.setObjectName("textOldRep")
        self.lblNewResponse = QtWidgets.QLabel(addResponse)
        self.lblNewResponse.setGeometry(QtCore.QRect(10, 310, 331, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.lblNewResponse.setFont(font)
        self.lblNewResponse.setObjectName("lblNewResponse")
        self.textNewRep = QtWidgets.QTextBrowser(addResponse)
        self.textNewRep.setGeometry(QtCore.QRect(10, 370, 341, 101))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.textNewRep.setFont(font)
        self.textNewRep.setReadOnly(False)
        self.textNewRep.setObjectName("textNewRep")
        self.lblTitre = QtWidgets.QLabel(addResponse)
        self.lblTitre.setGeometry(QtCore.QRect(10, 340, 51, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.lblTitre.setFont(font)
        self.lblTitre.setObjectName("lblTitre")
        self.textTitre = QtWidgets.QLineEdit(addResponse)
        self.textTitre.setGeometry(QtCore.QRect(60, 340, 291, 21))
        self.textTitre.setObjectName("textTitre")

        self.retranslateUi(addResponse)
        self.btnCancel.accepted.connect(addResponse.accept)
        self.btnCancel.rejected.connect(addResponse.reject)
        QtCore.QMetaObject.connectSlotsByName(addResponse)

    def retranslateUi(self, addResponse):
        _translate = QtCore.QCoreApplication.translate
        addResponse.setWindowTitle(_translate("addResponse", "IGN Espace Collaboratif : Ajout d\'une nouvelle réponse"))
        self.btnSend.setText(_translate("addResponse", "Envoyer la réponse"))
        self.lblStatut.setText(_translate("addResponse", "Statut"))
        self.lblMessage.setText(_translate("addResponse", "Message de la remarque"))
        self.lblOldResponse.setText(_translate("addResponse", "Réponse(s) antérieure(s)"))
        self.lblNewResponse.setText(_translate("addResponse", "Nouvelle réponse"))
        self.lblTitre.setText(_translate("addResponse", "Titre"))

