# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'FormSmartCutConfig_base.ui'
#
# Created by: PyQt5 UI code generator
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DialogSmartCutConfig(object):
    def setupUi(self, DialogSmartCutConfig):
        DialogSmartCutConfig.setObjectName("DialogSmartCutConfig")
        DialogSmartCutConfig.resize(550, 500)
        DialogSmartCutConfig.setStyleSheet("QDialog {background-color: rgb(255, 255, 255)}")
        self.verticalLayout = QtWidgets.QVBoxLayout(DialogSmartCutConfig)
        self.verticalLayout.setObjectName("verticalLayout")
        self.labelTitle = QtWidgets.QLabel(DialogSmartCutConfig)
        self.labelTitle.setWordWrap(True)
        self.labelTitle.setObjectName("labelTitle")
        self.verticalLayout.addWidget(self.labelTitle)
        self.labelDescription = QtWidgets.QLabel(DialogSmartCutConfig)
        self.labelDescription.setWordWrap(True)
        self.labelDescription.setObjectName("labelDescription")
        self.verticalLayout.addWidget(self.labelDescription)
        spacerItem = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem)
        self.groupBoxLayer = QtWidgets.QGroupBox(DialogSmartCutConfig)
        self.groupBoxLayer.setObjectName("groupBoxLayer")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBoxLayer)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.labelLayerInfo = QtWidgets.QLabel(self.groupBoxLayer)
        self.labelLayerInfo.setWordWrap(True)
        self.labelLayerInfo.setObjectName("labelLayerInfo")
        self.verticalLayout_2.addWidget(self.labelLayerInfo)
        self.listAvailableFields = QtWidgets.QListWidget(self.groupBoxLayer)
        self.listAvailableFields.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.listAvailableFields.setObjectName("listAvailableFields")
        self.verticalLayout_2.addWidget(self.listAvailableFields)
        self.btnRefreshLayer = QtWidgets.QPushButton(self.groupBoxLayer)
        self.btnRefreshLayer.setObjectName("btnRefreshLayer")
        self.verticalLayout_2.addWidget(self.btnRefreshLayer)
        self.verticalLayout.addWidget(self.groupBoxLayer)
        self.groupBoxUnique = QtWidgets.QGroupBox(DialogSmartCutConfig)
        self.groupBoxUnique.setObjectName("groupBoxUnique")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBoxUnique)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.labelUniqueInfo = QtWidgets.QLabel(self.groupBoxUnique)
        self.labelUniqueInfo.setWordWrap(True)
        self.labelUniqueInfo.setObjectName("labelUniqueInfo")
        self.verticalLayout_3.addWidget(self.labelUniqueInfo)
        self.listUniqueAttrs = QtWidgets.QListWidget(self.groupBoxUnique)
        self.listUniqueAttrs.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.listUniqueAttrs.setObjectName("listUniqueAttrs")
        self.verticalLayout_3.addWidget(self.listUniqueAttrs)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btnAddToUnique = QtWidgets.QPushButton(self.groupBoxUnique)
        self.btnAddToUnique.setObjectName("btnAddToUnique")
        self.horizontalLayout.addWidget(self.btnAddToUnique)
        self.btnRemoveFromUnique = QtWidgets.QPushButton(self.groupBoxUnique)
        self.btnRemoveFromUnique.setObjectName("btnRemoveFromUnique")
        self.horizontalLayout.addWidget(self.btnRemoveFromUnique)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.verticalLayout.addWidget(self.groupBoxUnique)
        self.buttonBox = QtWidgets.QDialogButtonBox(DialogSmartCutConfig)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(DialogSmartCutConfig)
        self.buttonBox.accepted.connect(DialogSmartCutConfig.accept)
        self.buttonBox.rejected.connect(DialogSmartCutConfig.reject)
        QtCore.QMetaObject.connectSlotsByName(DialogSmartCutConfig)

    def retranslateUi(self, DialogSmartCutConfig):
        _translate = QtCore.QCoreApplication.translate
        DialogSmartCutConfig.setWindowTitle(_translate("DialogSmartCutConfig", "Configuration - Découpe intelligente"))
        self.labelTitle.setText(_translate("DialogSmartCutConfig", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">Configuration de la découpe intelligente</span></p></body></html>"))
        self.labelDescription.setText(_translate("DialogSmartCutConfig", "Sélectionnez les attributs qui doivent rester uniques.\n"
"Lors d\'une découpe, ces attributs ne seront conservés que sur le plus grand polygone."))
        self.groupBoxLayer.setTitle(_translate("DialogSmartCutConfig", "Attributs de la couche active"))
        self.labelLayerInfo.setText(_translate("DialogSmartCutConfig", "<i>Aucune couche sélectionnée</i>"))
        self.btnRefreshLayer.setText(_translate("DialogSmartCutConfig", "⟳ Actualiser depuis la couche active"))
        self.groupBoxUnique.setTitle(_translate("DialogSmartCutConfig", "Attributs uniques configurés"))
        self.labelUniqueInfo.setText(_translate("DialogSmartCutConfig", "Ces attributs seront conservés uniquement sur le plus grand polygone:"))
        self.btnAddToUnique.setText(_translate("DialogSmartCutConfig", "⬇ Ajouter aux attributs uniques"))
        self.btnRemoveFromUnique.setText(_translate("DialogSmartCutConfig", "✖ Retirer"))
