# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'FormView_base.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_viewRemark(object):
    def setupUi(self, viewRemark):
        viewRemark.setObjectName("viewRemark")
        viewRemark.resize(365, 551)
        viewRemark.setMaximumSize(QtCore.QSize(365, 551))
        icon = QtGui.QIcon.fromTheme("IGN")
        viewRemark.setWindowIcon(icon)
        self.btnCancel = QtWidgets.QDialogButtonBox(viewRemark)
        self.btnCancel.setGeometry(QtCore.QRect(280, 520, 75, 23))
        self.btnCancel.setOrientation(QtCore.Qt.Horizontal)
        self.btnCancel.setStandardButtons(QtWidgets.QDialogButtonBox.Ok)
        self.btnCancel.setCenterButtons(False)
        self.btnCancel.setObjectName("btnCancel")
        self.verticalLayoutWidget = QtWidgets.QWidget(viewRemark)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(9, 10, 344, 381))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout_4 = QtWidgets.QFormLayout()
        self.formLayout_4.setObjectName("formLayout_4")
        self.lblStatut = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.lblStatut.setFont(font)
        self.lblStatut.setObjectName("lblStatut")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.lblStatut)
        self.textStatut = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.textStatut.setFont(font)
        self.textStatut.setObjectName("textStatut")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.textStatut)
        self.verticalLayout.addLayout(self.formLayout_4)
        self.lblMessage = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.lblMessage.setFont(font)
        self.lblMessage.setObjectName("lblMessage")
        self.verticalLayout.addWidget(self.lblMessage)
        self.textMessage = QtWidgets.QTextBrowser(self.verticalLayoutWidget)
        self.textMessage.setMaximumSize(QtCore.QSize(16777215, 110))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.textMessage.setFont(font)
        self.textMessage.setObjectName("textMessage")
        self.verticalLayout.addWidget(self.textMessage)
        self.lblOldResponse = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.lblOldResponse.setFont(font)
        self.lblOldResponse.setObjectName("lblOldResponse")
        self.verticalLayout.addWidget(self.lblOldResponse)
        self.textOldRep = QtWidgets.QTextBrowser(self.verticalLayoutWidget)
        self.textOldRep.setMinimumSize(QtCore.QSize(339, 179))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.textOldRep.setFont(font)
        self.textOldRep.setObjectName("textOldRep")
        self.verticalLayout.addWidget(self.textOldRep)
        self.btnDoc_0 = QtWidgets.QPushButton(viewRemark)
        self.btnDoc_0.setEnabled(False)
        self.btnDoc_0.setGeometry(QtCore.QRect(10, 400, 75, 23))
        self.btnDoc_0.setObjectName("btnDoc_0")
        self.lblCntCroquis = QtWidgets.QLabel(viewRemark)
        self.lblCntCroquis.setGeometry(QtCore.QRect(90, 430, 261, 16))
        self.lblCntCroquis.setObjectName("lblCntCroquis")
        self.btnCroquis = QtWidgets.QPushButton(viewRemark)
        self.btnCroquis.setGeometry(QtCore.QRect(10, 428, 75, 24))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/plugins/RipartPlugin/images/magicwand.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnCroquis.setIcon(icon)
        self.btnCroquis.setObjectName("btnCroquis")
        self.textEditCntCroquisDetail = QtWidgets.QTextEdit(viewRemark)
        self.textEditCntCroquisDetail.setEnabled(True)
        self.textEditCntCroquisDetail.setGeometry(QtCore.QRect(10, 458, 342, 50))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textEditCntCroquisDetail.sizePolicy().hasHeightForWidth())
        self.textEditCntCroquisDetail.setSizePolicy(sizePolicy)
        self.textEditCntCroquisDetail.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.textEditCntCroquisDetail.setLineWidth(0)
        self.textEditCntCroquisDetail.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEditCntCroquisDetail.setReadOnly(True)
        self.textEditCntCroquisDetail.setObjectName("textEditCntCroquisDetail")
        self.btnDoc_1 = QtWidgets.QPushButton(viewRemark)
        self.btnDoc_1.setEnabled(False)
        self.btnDoc_1.setGeometry(QtCore.QRect(90, 400, 75, 23))
        self.btnDoc_1.setObjectName("btnDoc_1")
        self.btnDoc_2 = QtWidgets.QPushButton(viewRemark)
        self.btnDoc_2.setEnabled(False)
        self.btnDoc_2.setGeometry(QtCore.QRect(170, 400, 75, 23))
        self.btnDoc_2.setObjectName("btnDoc_2")
        self.btnDoc_3 = QtWidgets.QPushButton(viewRemark)
        self.btnDoc_3.setEnabled(False)
        self.btnDoc_3.setGeometry(QtCore.QRect(250, 400, 75, 23))
        self.btnDoc_3.setObjectName("btnDoc_3")
        self.btnDoc_0.raise_()
        self.lblCntCroquis.raise_()
        self.btnCroquis.raise_()
        self.textEditCntCroquisDetail.raise_()
        self.btnCancel.raise_()
        self.verticalLayoutWidget.raise_()
        self.btnDoc_1.raise_()
        self.btnDoc_2.raise_()
        self.btnDoc_3.raise_()

        self.retranslateUi(viewRemark)
        self.btnCancel.accepted.connect(viewRemark.accept)
        self.btnCancel.rejected.connect(viewRemark.reject)
        QtCore.QMetaObject.connectSlotsByName(viewRemark)

    def retranslateUi(self, viewRemark):
        _translate = QtCore.QCoreApplication.translate
        viewRemark.setWindowTitle(_translate("viewRemark", "IGN Espace Collaboratif : Historique du signalement"))
        self.lblStatut.setText(_translate("viewRemark", "Statut"))
        self.textStatut.setText(_translate("viewRemark", "statut"))
        self.lblMessage.setText(_translate("viewRemark", "Message du signalement"))
        self.lblOldResponse.setText(_translate("viewRemark", "Réponse(s) antérieure(s)"))
        self.btnDoc_0.setText(_translate("viewRemark", "Document 1"))
        self.lblCntCroquis.setText(_translate("viewRemark", "Nombre de croquis sélectionnés: -"))
        self.btnCroquis.setToolTip(_translate("viewRemark", "<html><head/><body><p>Sélection/désélection des croquis associés à la remarque</p></body></html>"))
        self.btnCroquis.setText(_translate("viewRemark", "Croquis"))
        self.btnDoc_1.setText(_translate("viewRemark", "Document 2"))
        self.btnDoc_2.setText(_translate("viewRemark", "Document3"))
        self.btnDoc_3.setText(_translate("viewRemark", "Document 4"))

