# -*- coding: utf-8 -*-
from .qt_compat import BUTTONBOX_CANCEL, BUTTONBOX_SAVE, ORIENTATION_HORIZONTAL, PEN_NO_PEN, SIZEPOLICY_EXPANDING
# Form implementation generated from reading ui file 'FormChargerGuichet_base.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from qgis.PyQt import QtCore, QtGui, QtWidgets


class Ui_DialogChargerGuichet(object):
    def setupUi(self, DialogChargerGuichet):
        DialogChargerGuichet.setObjectName("DialogChargerGuichet")
        DialogChargerGuichet.resize(751, 707)
        DialogChargerGuichet.setStyleSheet("QDialog {background-color: rgb(255, 255, 255)}")
        self.buttonBox = QtWidgets.QDialogButtonBox(DialogChargerGuichet)
        self.buttonBox.setGeometry(QtCore.QRect(540, 670, 201, 32))
        self.buttonBox.setOrientation(ORIENTATION_HORIZONTAL)
        self.buttonBox.setStandardButtons(BUTTONBOX_CANCEL|BUTTONBOX_SAVE)
        self.buttonBox.setObjectName("buttonBox")
        self.labelMonGuichet = QtWidgets.QLabel(DialogChargerGuichet)
        self.labelMonGuichet.setGeometry(QtCore.QRect(10, 40, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.labelMonGuichet.setFont(font)
        self.labelMonGuichet.setObjectName("labelMonGuichet")
        self.labelFondsGeoportail = QtWidgets.QLabel(DialogChargerGuichet)
        self.labelFondsGeoportail.setGeometry(QtCore.QRect(10, 370, 131, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.labelFondsGeoportail.setFont(font)
        self.labelFondsGeoportail.setObjectName("labelFondsGeoportail")
        self.tableWidgetMonGuichet = QtWidgets.QTableWidget(DialogChargerGuichet)
        self.tableWidgetMonGuichet.setEnabled(True)
        self.tableWidgetMonGuichet.setGeometry(QtCore.QRect(10, 70, 731, 261))
        sizePolicy = QtWidgets.QSizePolicy(SIZEPOLICY_EXPANDING, SIZEPOLICY_EXPANDING)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidgetMonGuichet.sizePolicy().hasHeightForWidth())
        self.tableWidgetMonGuichet.setSizePolicy(sizePolicy)
        self.tableWidgetMonGuichet.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableWidgetMonGuichet.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.tableWidgetMonGuichet.setAutoScroll(True)
        self.tableWidgetMonGuichet.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerItem)
        self.tableWidgetMonGuichet.setShowGrid(False)
        self.tableWidgetMonGuichet.setGridStyle(PEN_NO_PEN)
        self.tableWidgetMonGuichet.setRowCount(0)
        self.tableWidgetMonGuichet.setColumnCount(3)
        self.tableWidgetMonGuichet.setObjectName("tableWidgetMonGuichet")
        self.tableWidgetMonGuichet.horizontalHeader().setVisible(True)
        self.tableWidgetMonGuichet.horizontalHeader().setCascadingSectionResizes(True)
        self.tableWidgetMonGuichet.horizontalHeader().setDefaultSectionSize(225)
        self.tableWidgetMonGuichet.horizontalHeader().setHighlightSections(False)
        self.tableWidgetMonGuichet.horizontalHeader().setMinimumSectionSize(30)
        self.tableWidgetMonGuichet.horizontalHeader().setStretchLastSection(False)
        self.tableWidgetMonGuichet.verticalHeader().setVisible(False)
        self.tableWidgetMonGuichet.verticalHeader().setCascadingSectionResizes(True)
        self.tableWidgetMonGuichet.verticalHeader().setDefaultSectionSize(37)
        self.tableWidgetMonGuichet.verticalHeader().setHighlightSections(False)
        self.tableWidgetMonGuichet.verticalHeader().setMinimumSectionSize(37)
        self.tableWidgetMonGuichet.verticalHeader().setStretchLastSection(False)
        self.tableWidgetFondsGeoportail = QtWidgets.QTableWidget(DialogChargerGuichet)
        self.tableWidgetFondsGeoportail.setGeometry(QtCore.QRect(10, 400, 731, 261))
        self.tableWidgetFondsGeoportail.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableWidgetFondsGeoportail.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.tableWidgetFondsGeoportail.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerItem)
        self.tableWidgetFondsGeoportail.setShowGrid(False)
        self.tableWidgetFondsGeoportail.setGridStyle(PEN_NO_PEN)
        self.tableWidgetFondsGeoportail.setColumnCount(3)
        self.tableWidgetFondsGeoportail.setObjectName("tableWidgetFondsGeoportail")
        self.tableWidgetFondsGeoportail.setRowCount(0)
        self.tableWidgetFondsGeoportail.horizontalHeader().setVisible(True)
        self.tableWidgetFondsGeoportail.horizontalHeader().setCascadingSectionResizes(True)
        self.tableWidgetFondsGeoportail.horizontalHeader().setDefaultSectionSize(225)
        self.tableWidgetFondsGeoportail.horizontalHeader().setHighlightSections(False)
        self.tableWidgetFondsGeoportail.horizontalHeader().setMinimumSectionSize(30)
        self.tableWidgetFondsGeoportail.horizontalHeader().setStretchLastSection(False)
        self.tableWidgetFondsGeoportail.verticalHeader().setVisible(False)
        self.tableWidgetFondsGeoportail.verticalHeader().setCascadingSectionResizes(True)
        self.tableWidgetFondsGeoportail.verticalHeader().setHighlightSections(False)
        self.tableWidgetFondsGeoportail.verticalHeader().setStretchLastSection(False)
        self.labelGroupeActif = QtWidgets.QLabel(DialogChargerGuichet)
        self.labelGroupeActif.setGeometry(QtCore.QRect(10, 10, 301, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.labelGroupeActif.setFont(font)
        self.labelGroupeActif.setText("")
        self.labelGroupeActif.setObjectName("labelGroupeActif")

        self.retranslateUi(DialogChargerGuichet)
        QtCore.QMetaObject.connectSlotsByName(DialogChargerGuichet)

    def retranslateUi(self, DialogChargerGuichet):
        _translate = QtCore.QCoreApplication.translate
        DialogChargerGuichet.setWindowTitle(_translate("DialogChargerGuichet", "Charger les couches de mon groupe"))
        self.labelMonGuichet.setText(_translate("DialogChargerGuichet", "Mon guichet"))
        self.labelFondsGeoportail.setText(_translate("DialogChargerGuichet", "Fonds Géoportail"))
