# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'FormCreerRemarque_base.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui
from qgis.PyQt import QtWidgets 

class Ui_dlgCreateRem(object):
    def setupUi(self, dlgCreateRem):
        dlgCreateRem.setObjectName("dlgCreateRem")
        dlgCreateRem.resize(432, 538)
        self.groupBoxProfil = QtWidgets.QGroupBox(dlgCreateRem)
        self.groupBoxProfil.setGeometry(QtCore.QRect(10, 10, 411, 481))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.groupBoxProfil.setFont(font)
        self.groupBoxProfil.setObjectName("groupBoxProfil")
        self.tabWidget = QtWidgets.QTabWidget(self.groupBoxProfil)
        self.tabWidget.setGeometry(QtCore.QRect(10, 50, 391, 231))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.tabWidget.setFont(font)
        self.tabWidget.setObjectName("tabWidget")
        self.tabTheme = QtWidgets.QWidget()
        self.tabTheme.setObjectName("tabTheme")
        self.treeWidget = QtWidgets.QTreeWidget(self.tabTheme)
        self.treeWidget.setGeometry(QtCore.QRect(0, 0, 391, 211))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.treeWidget.sizePolicy().hasHeightForWidth())
        self.treeWidget.setSizePolicy(sizePolicy)
        self.treeWidget.setItemsExpandable(True)
        self.treeWidget.setObjectName("treeWidget")
        self.tabWidget.addTab(self.tabTheme, "")
        self.tabOption = QtWidgets.QWidget()
        self.tabOption.setObjectName("tabOption")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.tabOption)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 10, 480, 121))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.checkBoxJoinCroquis = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.checkBoxJoinCroquis.setMaximumSize(QtCore.QSize(16777215, 15))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.checkBoxJoinCroquis.setFont(font)
        self.checkBoxJoinCroquis.setChecked(True)
        self.checkBoxJoinCroquis.setObjectName("checkBoxJoinCroquis")
        self.verticalLayout.addWidget(self.checkBoxJoinCroquis)
        self.checkBoxAttDoc = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.checkBoxAttDoc.setMaximumSize(QtCore.QSize(16777215, 15))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.checkBoxAttDoc.setFont(font)
        self.checkBoxAttDoc.setObjectName("checkBoxAttDoc")
        self.verticalLayout.addWidget(self.checkBoxAttDoc)
        self.lblDoc = QtWidgets.QLabel(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblDoc.sizePolicy().hasHeightForWidth())
        self.lblDoc.setSizePolicy(sizePolicy)
        self.lblDoc.setMaximumSize(QtCore.QSize(16777215, 10))
        font = QtGui.QFont()
        font.setItalic(True)
        self.lblDoc.setFont(font)
        self.lblDoc.setObjectName("lblDoc")
        self.verticalLayout.addWidget(self.lblDoc)
        self.line = QtWidgets.QFrame(self.verticalLayoutWidget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.horizontalLayout.setSpacing(2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.radioBtnUnique = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.radioBtnUnique.setMaximumSize(QtCore.QSize(180, 16777215))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.radioBtnUnique.setFont(font)
        self.radioBtnUnique.setChecked(True)
        self.radioBtnUnique.setObjectName("radioBtnUnique")
        self.horizontalLayout.addWidget(self.radioBtnUnique)
        self.radioBtnMultiple = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.radioBtnMultiple.setFont(font)
        self.radioBtnMultiple.setObjectName("radioBtnMultiple")
        self.horizontalLayout.addWidget(self.radioBtnMultiple)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.tabWidget.addTab(self.tabOption, "")
        self.textEditMessage = QtWidgets.QTextEdit(self.groupBoxProfil)
        self.textEditMessage.setGeometry(QtCore.QRect(10, 310, 391, 161))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.textEditMessage.setFont(font)
        self.textEditMessage.setObjectName("textEditMessage")
        self.lblMessage = QtWidgets.QLabel(self.groupBoxProfil)
        self.lblMessage.setGeometry(QtCore.QRect(10, 290, 51, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.lblMessage.setFont(font)
        self.lblMessage.setObjectName("lblMessage")
        self.lblProfilIcon = QtWidgets.QLabel(self.groupBoxProfil)
        self.lblProfilIcon.setGeometry(QtCore.QRect(370, 10, 41, 41))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.lblProfilIcon.setFont(font)
        self.lblProfilIcon.setText("")
        self.lblProfilIcon.setObjectName("lblProfilIcon")
        self.label = QtWidgets.QLabel(self.groupBoxProfil)
        self.label.setGeometry(QtCore.QRect(10, 30, 161, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.lblMessageError = QtWidgets.QLabel(self.groupBoxProfil)
        self.lblMessageError.setGeometry(QtCore.QRect(70, 290, 321, 16))
        self.lblMessageError.setText("")
        self.lblMessageError.setObjectName("lblMessageError")
        self.buttonBox = QtWidgets.QDialogButtonBox(dlgCreateRem)
        self.buttonBox.setGeometry(QtCore.QRect(260, 500, 156, 23))
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")

        self.retranslateUi(dlgCreateRem)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(dlgCreateRem)

    def retranslateUi(self, dlgCreateRem):
        _translate = QtCore.QCoreApplication.translate
        dlgCreateRem.setWindowTitle(_translate("dlgCreateRem", "IGN Espace Collaboratif : Créer un nouveau signalement"))
        self.groupBoxProfil.setTitle(_translate("dlgCreateRem", "Profil"))
        self.treeWidget.headerItem().setText(0, _translate("dlgCreateRem", "thème"))
        self.treeWidget.headerItem().setText(1, _translate("dlgCreateRem", "attribut"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabTheme), _translate("dlgCreateRem", "Thèmes"))
        self.checkBoxJoinCroquis.setText(_translate("dlgCreateRem", "Joindre un croquis"))
        self.checkBoxAttDoc.setText(_translate("dlgCreateRem", "Joindre un document"))
        self.lblDoc.setText(_translate("dlgCreateRem", "TextLabel"))
        self.radioBtnUnique.setText(_translate("dlgCreateRem", "Créer une remarque unique"))
        self.radioBtnMultiple.setText(_translate("dlgCreateRem", "Créer remarques distinctes"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabOption), _translate("dlgCreateRem", "Options"))
        self.lblMessage.setText(_translate("dlgCreateRem", "Message"))
        self.label.setText(_translate("dlgCreateRem", "Nouveau signalement"))

