# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'FormConnection_base.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ConnectionDialog(object):
    def setupUi(self, ConnectionDialog):
        ConnectionDialog.setObjectName("ConnectionDialog")
        ConnectionDialog.setWindowModality(QtCore.Qt.NonModal)
        ConnectionDialog.resize(400, 123)
        icon = QtGui.QIcon.fromTheme("ign")
        ConnectionDialog.setWindowIcon(icon)
        ConnectionDialog.setModal(False)
        self.buttonBox = QtWidgets.QDialogButtonBox(ConnectionDialog)
        self.buttonBox.setGeometry(QtCore.QRect(210, 80, 161, 32))
        self.buttonBox.setFocusPolicy(QtCore.Qt.TabFocus)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setCenterButtons(True)
        self.buttonBox.setObjectName("buttonBox")
        self.lblLogo = QtWidgets.QLabel(ConnectionDialog)
        self.lblLogo.setGeometry(QtCore.QRect(10, 10, 71, 71))
        self.lblLogo.setText("")
        self.lblLogo.setPixmap(QtGui.QPixmap("images/logo_IGN.png"))
        self.lblLogo.setScaledContents(True)
        self.lblLogo.setWordWrap(False)
        self.lblLogo.setOpenExternalLinks(False)
        self.lblLogo.setObjectName("lblLogo")
        self.lblPwd = QtWidgets.QLabel(ConnectionDialog)
        self.lblPwd.setGeometry(QtCore.QRect(91, 49, 111, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lblPwd.setFont(font)
        self.lblPwd.setObjectName("lblPwd")
        self.lineEditPwd = QtWidgets.QLineEdit(ConnectionDialog)
        self.lineEditPwd.setGeometry(QtCore.QRect(210, 49, 161, 20))
        self.lineEditPwd.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEditPwd.setObjectName("lineEditPwd")
        self.lblLogin = QtWidgets.QLabel(ConnectionDialog)
        self.lblLogin.setGeometry(QtCore.QRect(91, 20, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lblLogin.setFont(font)
        self.lblLogin.setObjectName("lblLogin")
        self.lineEditLogin = QtWidgets.QLineEdit(ConnectionDialog)
        self.lineEditLogin.setGeometry(QtCore.QRect(210, 20, 161, 20))
        self.lineEditLogin.setObjectName("lineEditLogin")

        self.retranslateUi(ConnectionDialog)
        self.buttonBox.accepted.connect(ConnectionDialog.accept)
        self.buttonBox.rejected.connect(ConnectionDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(ConnectionDialog)
        ConnectionDialog.setTabOrder(self.lineEditLogin, self.lineEditPwd)

    def retranslateUi(self, ConnectionDialog):
        _translate = QtCore.QCoreApplication.translate
        ConnectionDialog.setWindowTitle(_translate("ConnectionDialog", "Connexion à l\'Espace collaboratif"))
        self.lblPwd.setText(_translate("ConnectionDialog", "Votre mot de passe"))
        self.lblLogin.setText(_translate("ConnectionDialog", "Votre login"))
