# -*- coding: utf-8 -*-
"""
/***************************************************************************
 RipartPlugin
                                 A QGIS plugin
 ripart QGIS3
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2018-11-12
        git sha              : $Format:%H$
        copyright            : (C) 2018 by IGN
        email                : @ign.fr
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
# from __future__ import absolute_import

# from future import standard_library
# standard_library.install_aliases()
from builtins import str
from builtins import range
# from builtins import object
import os.path

from PyQt5.QtGui import QColor

from .core.RipartLoggerCl import RipartLogger

from qgis.PyQt.QtCore import QSettings, QTranslator, qVersion, QCoreApplication, QObject, Qt
from qgis.PyQt import QtGui, uic
from qgis.PyQt.QtWidgets import QAction, QMenu, QMessageBox, QToolButton, QApplication
from qgis.PyQt.QtGui import QIcon
# from qgis.core import *
from qgis.core import QgsProject, QgsMessageLog, QgsWkbTypes, QgsCoordinateReferenceSystem, \
    QgsVectorLayer, QgsDataSourceUri, QgsSymbol, QgsFeatureRenderer, QgsRuleBasedRenderer
import configparser

import urllib

# Initialize Qt resources from file resources.py
from . import resources

# modules ripart
from .FormChargerGuichet import FormChargerGuichet
from .FormConnexion_dialog import FormConnexionDialog
from .FormInfo import FormInfo
from .FormConfigure import FormConfigure
from .Contexte import Contexte
from .core.Client import Client
from .ImporterRipart import ImporterRipart
from .RepondreRipart import RepondreRipart
from .CreerRipart import CreerRipart
from .Magicwand import Magicwand
from .RipartHelper import RipartHelper
from .core.NoProfileException import NoProfileException
from .CompterGuichet import CompterGuichet

import logging


class RipartPlugin:
    """QGIS Plugin Implementation."""

    context = None
    logger = None
    ripartLogger = None

    def __init__(self, iface):
        """Constructor.

        :param iface: An interface instance that will be passed to this class
            which provides the hook by which you can manipulate the QGIS
            application at run time.
        :type iface: QgsInterface
        """
        self.ripartLogger = RipartLogger("RipartPlugin")
        self.logger = self.ripartLogger.getRipartLogger()

        # Save reference to the QGIS interface
        self.iface = iface
        # initialize plugin directory
        self.plugin_dir = os.path.dirname(__file__)
        # initialize locale
        locale = QSettings().value('locale/userLocale')[0:2]
        locale_path = os.path.join(
            self.plugin_dir,
            'i18n',
            'RipartPlugin_{}.qm'.format(locale))

        if os.path.exists(locale_path):
            self.translator = QTranslator()
            self.translator.load(locale_path)

            if qVersion() > '4.3.3':
                QCoreApplication.installTranslator(self.translator)

        # Create the dialog (after translation) and keep reference
        self.dlgConnexion = FormConnexionDialog()

        # La toolbar du plugin
        self.actions = []
        self.menu = self.tr(u'&IGN_Espace_Collaboratif')

        self.toolbar = self.iface.addToolBar(u'RipartPlugin')
        self.toolbar.setObjectName(u'RipartPlugin')

    # noinspection PyMethodMayBeStatic
    def tr(self, message):
        """Get the translation for a string using Qt translation API.

        We implement this ourselves since we do not inherit QObject.

        :param message: String for translation.
        :type message: str, QString

        :returns: Translated version of message.
        :rtype: QString
        """
        # noinspection PyTypeChecker,PyArgumentList,PyCallByClass
        return QCoreApplication.translate('RipartPlugin', message)

    def add_action(
            self,
            icon_path,
            text,
            callback,
            enabled_flag=True,
            add_to_menu=True,
            add_to_toolbar=True,
            status_tip=None,
            whats_this=None,
            parent=None):
        """Add a toolbar icon to the toolbar.

        :param icon_path: Path to the icon for this action. Can be a resource
            path (e.g. ':/plugins/foo/bar.png') or a normal file system path.
        :type icon_path: str

        :param text: Text that should be shown in menu items for this action.
        :type text: str

        :param callback: Function to be called when the action is triggered.
        :type callback: function

        :param enabled_flag: A flag indicating if the action should be enabled
            by default. Defaults to True.
        :type enabled_flag: bool

        :param add_to_menu: Flag indicating whether the action should also
            be added to the menu. Defaults to True.
        :type add_to_menu: bool

        :param add_to_toolbar: Flag indicating whether the action should also
            be added to the toolbar. Defaults to True.
        :type add_to_toolbar: bool

        :param status_tip: Optional text to show in a popup when mouse pointer
            hovers over the action.
        :type status_tip: str

        :param parent: Parent widget for the new action. Defaults None.
        :type parent: QWidget

        :param whats_this: Optional text to show in the status bar when the
            mouse pointer hovers over the action.

        :returns: The action that was created. Note that the action is also
            added to self.actions list.
        :rtype: QAction
        """
        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip is not None:
            action.setStatusTip(status_tip)

        if whats_this is not None:
            action.setWhatsThis(whats_this)

        if add_to_toolbar:
            self.toolbar.addAction(action)

        if add_to_menu:
            self.iface.addPluginToMenu(
                self.menu,
                action)

        self.actions.append(action)

        return action

    def initGui(self):
        """Create the menu entries and toolbar icons inside the QGIS GUI."""

        icon_path = ':/plugins/RipartPlugin/images/connect.png'
        self.add_action(
            icon_path,
            text=self.tr(u'Se connecter a l\'Espace Collaboratif'),
            callback=self.run,
            status_tip=self.tr(u'Se connecter a l\'Espace Collaboratif'),
            parent=self.iface.mainWindow())

        icon_path = ':/plugins/RipartPlugin/images/update.png'
        self.add_action(
            icon_path,
            text=self.tr(u'Télécharger les signalements'),
            callback=self.downloadRemarks,
            status_tip=self.tr(u'Télécharger les signalements'),
            parent=self.iface.mainWindow())

        icon_path = ':/plugins/RipartPlugin/images/viewRem.png'
        self.add_action(
            icon_path,
            text=self.tr(u'Voir le signalement'),
            callback=self.viewRem,
            status_tip=self.tr(u'Voir le signalement'),
            parent=self.iface.mainWindow())

        icon_path = ':/plugins/RipartPlugin/images/answer.png'
        self.add_action(
            icon_path,
            text=self.tr(u'Répondre à un signalement'),
            callback=self.answerToRemark,
            status_tip=self.tr(u'Répondre à un signalement'),
            parent=self.iface.mainWindow())

        icon_path = ':/plugins/RipartPlugin/images/create.png'
        self.add_action(
            icon_path,
            text=self.tr(u'Créer un nouveau signalement'),
            callback=self.createRemark,
            status_tip=self.tr(u'Créer un nouveau signalement'),
            parent=self.iface.mainWindow())

        icon_path = ':/plugins/RipartPlugin/images/cleaning.png'
        self.add_action(
            icon_path,
            text=self.tr(u'Supprimer les signalements de la carte en cours'),
            callback=self.removeRemarks,
            status_tip=self.tr(u'Supprimer les signalements de la carte en cours'),
            parent=self.iface.mainWindow())

        icon_path = ':/plugins/RipartPlugin/images/magicwand.png'
        self.add_action(
            icon_path,
            text=self.tr(u'Voir les objets associés'),
            callback=self.magicwand,
            status_tip=self.tr(u'Voir les objets associés'),
            parent=self.iface.mainWindow())

        icon_path = ':/plugins/RipartPlugin/images/charger.png'
        self.add_action(
            icon_path,
            text=self.tr(u'Charger les couches de mon groupe'),
            callback=self.chargerGuichet,
            status_tip=self.tr(u'Charger les couches de mon groupe'),
            parent=self.iface.mainWindow())

        # icon_path = ':/plugins/RipartPlugin/images/compter.png'
        # self.add_action(
        #     icon_path,
        #     text=self.tr(u'Compter les modifications'),
        #     callback=self.compterModifications,
        #     status_tip=self.tr(u'Compter les modifications'),
        #     parent=self.iface.mainWindow())
        #
        # icon_path = ':/plugins/RipartPlugin/images/synchroniser.png'
        # self.add_action(
        #     icon_path,
        #     text=self.tr(u'Synchroniser'),
        #     callback=self.synchroniserDonnees,
        #     status_tip=self.tr(u'Synchroniser'),
        #     parent=self.iface.mainWindow())

        self.config = QAction(QIcon(":/plugins/RipartPlugin/images/config.png"), u"Configurer le plugin",
                              self.iface.mainWindow())
        self.help = QAction(QIcon(":/plugins/RipartPlugin/images/Book.png"), "Ouvrir le manuel utilisateur du plugin",
                            self.iface.mainWindow())
        self.log = QAction(QIcon(":/plugins/RipartPlugin/images/Log.png"), "Ouvrir le fichier de log du plugin",
                           self.iface.mainWindow())
        self.about = QAction(QIcon(":/plugins/RipartPlugin/images/About.png"), "A propos du plugin",
                             self.iface.mainWindow())

        self.config.triggered.connect(self.configurePref)
        self.config.setStatusTip(self.tr(u"Ouvre la fenêtre de configuration du plugin."))

        self.about.triggered.connect(self.ripAbout)
        self.help.triggered.connect(self.showHelp)
        self.log.triggered.connect(self.showLog)

        self.helpMenu = QMenu("Aide")
        self.helpMenu.addAction(self.config)
        self.helpMenu.addAction(self.help)
        self.helpMenu.addAction(self.log)
        self.helpMenu.addAction(self.about)
        self.toolButton2 = QToolButton()
        self.toolButton2.setMenu(self.helpMenu)
        self.toolButton2.setPopupMode(QToolButton.InstantPopup)
        self.toolButton2.setToolButtonStyle(Qt.ToolButtonTextOnly)
        self.toolButton2.setText("Aide")

        self.toolbar.addWidget(self.toolButton2)

    def chargerGuichet(self):
        try:
            print("Chargement des couches du groupe utilisateur")
            self.context = Contexte.getInstance(self, QgsProject)
            if self.context is None:
                return

            # Les profils serveur/client se correspondent-ils ?
            #self.context.checkProfilServeurClient()

            dlgChargerGuichet = FormChargerGuichet(self.context)
            if dlgChargerGuichet.context.profil is not None:
                if len(dlgChargerGuichet.context.profil.infosGeogroupes) == 1 and \
                        len(dlgChargerGuichet.context.profil.infosGeogroupes[0].layers) == 0 :
                    raise Exception(u"Votre groupe n'a pas paramétré sa carte, il n'y a pas de données à charger.")

            dlgChargerGuichet.exec_()

        except Exception as e:
            self.logger.error(format(e))
            self.context.iface.messageBar(). \
                pushMessage("Remarque",
                            str(e), \
                            level=1, duration=5)
            QApplication.setOverrideCursor(Qt.ArrowCursor)

    def compterModifications(self):
        print("Compter les modifications")
        cptg = CompterGuichet()
        cptg.doCount()

    def synchroniserDonnees(self):
        '''print("Synchroniser les données")
        self.context = Contexte.getInstance(self, QgsProject)
        if self.context != None:
            if not self.context.getVisibilityLayersFromGroupeActif():
                self.context.iface.messageBar(). \
                    pushMessage("Remarque",
                                "Pas de couche(s) éditable(s)", \
                                level=2, duration=5)
                return'''
        '''self.context = Contexte.getInstance(self, QgsProject)
        layer = self.context.iface.activeLayer()
        fields = layer.fields()
        for field in fields:
            name = field.name()
            print(name)
            index = fields.indexOf(name)
            ews = layer.editorWidgetSetup(index)
            field.constraints().constraintExpression()
            print("Type:", ews.type())
            print("Config:", ews.config())
            print(field.constraints().constraintExpression())
            print(layer.expressionField(index))'''

        '''context = Contexte.getInstance(self, QgsProject)
        root = context.QgsProject.instance().layerTreeRoot()
        order = root.customLayerOrder()
        print("order : {}".format(order))
        print("---------------------")
        layers = QgsProject.instance().mapLayers()
        for key in layers:
            order.insert(0, order.pop())  # Last layer to first position
        print("order : {}".format(order))
        root.setCustomLayerOrder(order)'''

        '''listLayerOrder = root.layerOrder() #QgsMapLayer
        for layer in listLayerOrder:
            print(layer.name())
        print('-----------------')

        nodesGroup = root.findGroups()
        for nodeGroup in nodesGroup:
            listFindLayers = nodeGroup.findLayers()
            for findLayer in listFindLayers:
                fl = findLayer.layer()
                print(fl.name())
        print('-----------------')

        listGeoportail = []
        #QgsMapLayer
        listCustomLayerOrder = []
        for layer in listLayerOrder:
            #trouve = False
            lName = layer.name()
            if lName.find('IGN') != -1:
                listGeoportail.append(layer.id())
            else:
                listCustomLayerOrder.append(layer.id())
            for qgsLayerTreeLayer in listFindLayers:
                ltl = qgsLayerTreeLayer.layer()
                if lName == ltl.name():
                    listCustomLayerOrder.append(layer)
                    trouve = True
                    break;
            if trouve is False:
                listGeoportail.append(layer)

        listCustomLayerOrder.extend(listGeoportail)
        for c in listCustomLayerOrder:
            print(c.name())

        root.setCustomLayerOrder(listCustomLayerOrder)
        context.mapCan.refresh()'''

    def unload(self):

        log = logging.getLogger()

        logs = logging.Logger.manager.loggerDict
        cntLogs = len(logs)

        for lg in logs:
            logger = logs[lg]
            if isinstance(logger, logging.Logger):
                handlers = logger.handlers
                cntHandlers = len(logger.handlers)
                for i in range(cntHandlers - 1, -1, -1):
                    try:
                        if os.path.basename(handlers[i].baseFilename)[-10:] == u"plugin_espaceco.log":
                            handlers[i].close()
                            logger.removeHandler(handlers[i])
                    except AttributeError as e:
                        continue

        logdir = os.path.join(os.path.dirname(os.path.realpath(__file__)), 'logs')
        if os.path.exists(logdir):
            for f in os.listdir(logdir):
                file = open(os.path.join(logdir, f), 'r+')
                file.close()
                try:
                    os.remove(os.path.join(logdir, f))
                except Exception as e:
                    self.logger.error(format(e))

        """Removes the plugin menu item and icon from QGIS GUI."""
        for action in self.actions:
            self.iface.removePluginMenu(
                self.tr(u'&IGN_Espace_Collaboratif'),
                action)
            self.iface.removeToolBarIcon(action)
            # action.setVisible(False)
        del self.toolbar

    def run(self):
        """Fenêtre de connexion"""

        self.context = Contexte.getInstance(self, QgsProject)
        if self.context is None:
            return

        if self.context:
            res = self.context.getConnexionRipart(newLogin=True)

        if not res:
            self.logger.debug("cancel")

    def downloadRemarks(self):
        """Downloads remarks
        """
        try:
            self.context = Contexte.getInstance(self, QgsProject)
            if self.context is None:
                return

            # Les profils serveur/client se correspondent-ils ?
            #self.context.checkProfilServeurClient()

            importRipart = ImporterRipart(self.context)
            result = importRipart.doImport()
            if result == 0:
                return
        except NoProfileException as e:
            self.context.iface.messageBar().clearWidgets()
            self.logger.error(format(e))
            self.context.iface.messageBar(). \
                pushMessage("Remarque",
                            format(e),
                            level=2, duration=5)
            QApplication.setOverrideCursor(Qt.ArrowCursor)
        except Exception as e:
            self.logger.error(format(e))
            self.context.iface.messageBar(). \
                pushMessage("Erreur",
                            u"Un problème est survenu dans le téléchargement des signalements",
                            level=2, duration=5)
            QApplication.setOverrideCursor(Qt.ArrowCursor)

    def connectToRipart(self, context):
        """Connection to the ripart service 
        """
        client = Client(context.urlHostRipart, context.login, context.pwd, context.proxy, context.clegeoportail)
        return client

    def answerToRemark(self):
        """Answer to a remark
        """
        try:
            self.context = Contexte.getInstance(self, QgsProject)
            if self.context is None:
                return

            # Les profils serveur/client se correspondent-ils ?
            #self.context.checkProfilServeurClient()

            reponse = RepondreRipart(self.context)
            reponse.do()
        except Exception as e:
            self.context.iface.messageBar(). \
                pushMessage("Erreur",
                            u"Un problème est survenu lors de l'ajout de la réponse ou lors de la connexion avec l'Espace Collaboratif. Veuillez réessayer.", \
                            level=2, duration=5)

    def createRemark(self):
        """Create a new remark
        """
        try:
            self.context = Contexte.getInstance(self, QgsProject)
            if self.context is None:
                return

            # Les profils serveur/client se correspondent-ils ?
            #self.context.checkProfilServeurClient()

            create = CreerRipart(self.context)
            create.do()
        except Exception as e:
            self.context.iface.messageBar(). \
                pushMessage("Erreur",
                            u"Un problème est survenu lors de la création du signalement", \
                            level=2, duration=5)

    def removeRemarks(self):
        """Remove all remarks from current map
        (empty the tables from ripart table of the sqlite DB)
        """
        try:
            self.context = Contexte.getInstance(self, QgsProject)
            if self.context is None:
                return
            message = u"Êtes-vous sûr de vouloir supprimer les signalements de la carte en cours?"
            reply = QMessageBox.question(None, 'IGN Espace Collaboratif', message, QMessageBox.Yes, QMessageBox.No)
            if reply == QMessageBox.Yes:
                self.context.emptyAllRipartLayers()
            else:
                return

        except Exception as e:
            self.context.iface.messageBar(). \
                pushMessage("Erreur",
                            u"Un problème est survenu lors de la suppression des signalements", \
                            level=2, duration=5)

    def configurePref(self):
        """Lance la fenêtre de configuration des préférences 
        """

        try:
            self.context = Contexte.getInstance(self, QgsProject)
            if self.context is None:
                return

            self.context.checkConfigFile()
            self.dlgConfigure = FormConfigure(context=self.context)

            self.dlgConfigure.exec_()

        except (Exception) as e:
            self.logger.error(format(e))
            self.context.iface.messageBar(). \
                pushMessage("Erreur",
                            u"Un problème est survenu dans le chargement de la configuration." + format(e), \
                            level=2, duration=5)

    def magicwand(self):
        """Sélectionne le/les signalement(s) associé(s) au(x) croquis sélectionnés 
          ou le/les croquis associé(s) au signalement sélectionné.
          On ne peut pas sélectionnner des signalements et des croquis (soit signalements, soit croquis)  
        """
        try:
            self.context = Contexte.getInstance(self, QgsProject)
            if self.context is None:
                return
            magicw = Magicwand(self.context)
            magicw.selectRipartObjects()

        except Exception as e:
            self.logger.error("magicWand " + format(e))

    def viewRem(self):
        """Visualisation du signalement (message, réponses et statut)
        """
        try:
            self.context = Contexte.getInstance(self, QgsProject)
            if self.context is None:
                return

            reponse = RepondreRipart(self.context)
            self.formView = reponse.do(isView=True)

        except Exception as e:
            self.logger.error("viewRem " + format(e))
            self.context.iface.messageBar(). \
                pushMessage("Erreur",
                            u"lors de la connexion avec l'Espace Collaboratif. Veuillez réessayer.", \
                            level=2, duration=5)

    def ripAbout(self):
        """Montre la fenêtre "about" avec les informations de version du plugin 
        """
        version = '0.'
        date = '2018'

        file_path = os.path.abspath(os.path.join(
            os.path.dirname(__file__), 'metadata.txt'))

        parser = configparser.ConfigParser()
        parser.optionxform = str
        parser.read(file_path)
        if parser.has_section('general'):
            try:
                version = parser.get('general', 'version')
                date = parser.get('general', 'date')
            except Exception as e:
                self.logger.error("No version/date in metadata")

        dlgInfo = FormInfo()
        dlgInfo.textInfo.setText(u"<b>Plugin Espace Collaboratif</b>")
        dlgInfo.textInfo.append(u"<br/><b>ATTENTION </b></br>"
                                    u"<br><br>Vous utilisez une version dépréciée du plugin Espace collaboratif pour QGIS. "
                                    u"Pour obtenir la dernière version, merci de vous connecter au nouveau dépôt d'extensions Espace collaboratif : </br>"
                                    u"<br><b>https://espacecollaboratif.ign.fr/plugins/plugin-qgis.xml </b></br>"
                                    u"<br><br>Plus de détails sur la procédure d'installation ici : https://espacecollaboratif.ign.fr/plugins/qgis</br>"
                                    u"<br></br><br>L'ancien dépôt d'extensions logiciels.ign.fr disparaîtra définitivement le 15/03/2022.</br>")
        dlgInfo.textInfo.append(u"<br/>Version: " + version)
        dlgInfo.textInfo.append(u"\u00A9 IGN - " + date)

        dlgInfo.exec_()

    # @TODO !!! lien vers le bon manuel (à partir de http://logiciels.ign.fr)!!!
    def showHelp(self):
        """Ouvre le document d'aide utilisateur   
        """
        #file_path = "http://logiciels.ign.fr/IMG/pdf/enr_espace_co_plugin_pour_qgis.pdf"
        file_path = os.path.abspath(os.path.join(os.path.dirname(__file__),"files","ENR_espace_co_plugin_pour_qgis.pdf"))

        RipartHelper.open_file(file_path)

        # TODO lien web
        # os.startfile("http://logiciels.ign.fr/IMG/pdf/add-in-ripart_1-0.pdf")

    def showLog(self):
        """Ouvre le dernier fichier de log
        """
        logpath = self.ripartLogger.getLogpath()
        if logpath != None:
            RipartHelper.open_file(logpath)
