# -*- coding: utf-8 -*-
"""
/***************************************************************************
 RipartPlugin
                                 A QGIS plugin
 ripart QGIS3
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2018-11-12
        git sha              : $Format:%H$
        copyright            : (C) 2018 by IGN
        email                : @ign.fr
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
from .qt_compat import MSGBOX_NO, MSGBOX_YES, TOOLBUTTON_POPUP_INSTANT, MSG_LEVEL_WARNING, MSG_LEVEL_CRITICAL

from builtins import str
from builtins import range
import os.path
import configparser
import logging

from qgis.PyQt.QtGui import QIcon
from qgis.PyQt.QtCore import QSettings, QTranslator, qVersion, QCoreApplication, Qt
from qgis.PyQt.QtWidgets import QAction, QMenu, QMessageBox, QToolButton, QApplication
from qgis.core import QgsProject

from .core.BBox import BBox
from .core.WfsPost import WfsPost
from .core.RipartLoggerCl import RipartLogger
from .core.SQLiteManager import SQLiteManager
from .core import ConstanteRipart as cst
from .core.NoProfileException import NoProfileException
from .core.WfsGet import WfsGet
from .core.ProgressBar import ProgressBar

# Initialize Qt resources from file resources.py
from . import resources

# modules ripart
from .FormChargerGuichet import FormChargerGuichet
from .FormInfo import FormInfo
from .FormConfigure import FormConfigure
from .Contexte import Contexte
from .ImporterRipart import ImporterRipart
from .SeeReport import SeeReport
from .CreerRipart import CreerRipart
from .Magicwand import Magicwand
from .RipartHelper import RipartHelper
from .ReplyReport import ReplyReport


class RipartPlugin:
    """QGIS Plugin Implementation."""
    context = None
    logger = None
    ripartLogger = None

    def __init__(self, iface):
        """
        Constructor.

        :param iface: A QGIS interface instance that will be passed to this class
            which provides the hook by which you can manipulate the QGIS
            application at run time.
        :type iface: QgsInterface
        """
        self.ripartLogger = RipartLogger("RipartPlugin")
        self.logger = self.ripartLogger.getRipartLogger()

        # Save reference to the QGIS interface
        self.iface = iface

        self.config = QAction(
            QIcon(":/plugins/RipartPlugin/images/config.png"),
            u"Configurer le plugin",
            self.iface.mainWindow()
        )
        self.help = QAction(
            QIcon(":/plugins/RipartPlugin/images/Book.png"),
            "Ouvrir le manuel utilisateur du plugin",
            self.iface.mainWindow()
        )
        self.log = QAction(
            QIcon(":/plugins/RipartPlugin/images/Log.png"),
            "Ouvrir le fichier de log du plugin",
            self.iface.mainWindow()
        )
        self.about = QAction(
            QIcon(":/plugins/RipartPlugin/images/About.png"),
            "A propos du plugin",
            self.iface.mainWindow()
        )

        # initialize plugin directory
        self.plugin_dir = os.path.dirname(__file__)

        # initialize locale
        locale_value = QSettings().value('locale/userLocale')
        if isinstance(locale_value, str) and len(locale_value) >= 2:
            locale = locale_value[0:2]
        else:
            locale = 'fr'
        locale_path = os.path.join(
            self.plugin_dir,
            'i18n',
            'RipartPlugin_{}.qm'.format(locale)
        )

        if os.path.exists(locale_path):
            self.translator = QTranslator()
            self.translator.load(locale_path)

            if qVersion() > '4.3.3':
                QCoreApplication.installTranslator(self.translator)

        # La toolbar du plugin
        self.actions = []
        self.menu = self.tr(u'&IGN_Espace_Collaboratif')
        self.toolbar = self.iface.addToolBar(u'RipartPlugin')
        self.toolbar.setObjectName(u'RipartPlugin')

        # Connexions de signaux
        self.iface.projectRead.connect(self.connectProjectRead)
        QgsProject.instance().layerWasAdded.connect(self.connectLayerWasAdded)

        self.libelle_transaction = None

    def unload(self):
        try:
            self.iface.projectRead.disconnect(self.connectProjectRead)
        except Exception:
            pass

        try:
            QgsProject.instance().layerWasAdded.disconnect(self.connectLayerWasAdded)
        except Exception:
            pass

        logs = logging.Logger.manager.loggerDict
        for lg in logs:
            logger = logs[lg]
            if isinstance(logger, logging.Logger):
                handlers = logger.handlers
                cntHandlers = len(logger.handlers)
                for i in range(cntHandlers - 1, -1, -1):
                    try:
                        if os.path.basename(handlers[i].name.baseFilename)[-10:] == u"plugin_espaceco.log":
                            handlers[i].close()
                            logger.removeHandler(handlers[i])
                    except AttributeError:
                        continue

        logdir = os.path.join(os.path.dirname(os.path.realpath(__file__)), 'logs')
        if os.path.exists(logdir):
            for f in os.listdir(logdir):
                file = open(os.path.join(logdir, f), 'r+')
                file.close()
                try:
                    os.remove(os.path.join(logdir, f))
                except Exception as e:
                    self.logger.error(format(e))

        # Supprime les actions du menu et de la toolbar
        for action in self.actions:
            self.iface.removePluginMenu(
                self.tr(u'&IGN_Espace_Collaboratif'),
                action
            )
            self.iface.removeToolBarIcon(action)

        del self.toolbar

    def getlibelletransaction(self):
        return self.libelle_transaction

    def _get_context(self):
        """
        Récupère le contexte courant sans provoquer d'écriture projet.
        """
        if self.context is None:
            self.context = Contexte.getInstance(self, QgsProject)
        return self.context

    def _project_has_ripart_group(self):
        """
        Détection non destructive d'un groupe Ripart déjà présent dans l'arbre.
        """
        try:
            root = QgsProject.instance().layerTreeRoot()
            for ng in root.findGroups():
                name = ng.name() or ""
                if cst.ESPACECO in name or "ESPACECO" in name.upper() or "ESPACE CO" in name.upper():
                    return True
        except Exception as e:
            self.logger.debug("_project_has_ripart_group: {}".format(e))
        return False

    def connectProjectRead(self):
        """
        IMPORTANT :
        - ne crée jamais XML / SQLite / styles à l'ouverture d'un projet
        - ne travaille automatiquement que sur un projet qui semble déjà Ripart
        """
        try:
            context = self._get_context()
            if context is None:
                return

            if not self._project_has_ripart_group():
                self.logger.debug("connectProjectRead: projet standard, aucune initialisation Ripart")
                return

            self._show_deprecation_warning()

            uri = context.getUriDatabaseSqlite()
            if uri is None:
                self.logger.debug("connectProjectRead: groupe Ripart détecté mais base absente")
                return

            if not SQLiteManager.isTableExist(cst.TABLEOFTABLES):
                self.logger.debug("connectProjectRead: TABLEOFTABLES absente")
                return

            root = QgsProject.instance().layerTreeRoot()
            nodesGroup = root.findGroups()
            for ng in nodesGroup:
                if ng.name().find(cst.ESPACECO) != -1 and context.client is None:
                    message = (
                        "Votre projet contient des couches de l'Espace collaboratif IGN. "
                        "Pour continuer à les utiliser, nous vous conseillons de vous y connecter.\n"
                        "Voulez-vous vous connecter à l'Espace collaboratif ? "
                    )
                    reply = QMessageBox.question(
                        self.iface.mainWindow(),
                        cst.IGNESPACECO,
                        message,
                        MSGBOX_YES,
                        MSGBOX_NO
                    )

                    if reply == MSGBOX_YES:
                        if self.context is None:
                            return
                        if self.context.client is None or self.context.profil is None:
                            if not self.context.getConnexionRipart(newLogin=True):
                                return

                    elif reply == MSGBOX_NO:
                        projectLayers = QgsProject.instance().mapLayers()
                        for _, v in projectLayers.items():
                            if not self.searchSpecificLayer(v.name()):
                                continue
                            self.connectSpecificSignals(v)
                    break

        except Exception as e:
            self.logger.error("connectProjectRead: {}".format(e))

    def connectLayerWasAdded(self, layer):
        """
        Ne branche des signaux qu'à des couches déjà identifiées comme Ripart.
        Aucune initialisation destructive ici.
        """
        try:
            if layer is None:
                return

            context = self._get_context()
            if context is None:
                return

            uri = context.getUriDatabaseSqlite()
            if uri is None:
                return

            if not SQLiteManager.isTableExist(cst.TABLEOFTABLES):
                return

            if not self.searchSpecificLayer(layer.name()):
                return

            self.connectSpecificSignals(layer)

        except Exception as e:
            self.logger.error("connectLayerWasAdded: {}".format(e))

    def connectSpecificSignals(self, layer):
        if layer is None:
            return

        try:
            layer.nameChanged.disconnect(self.connectNameChanged)
        except Exception:
            pass
        try:
            layer.beforeCommitChanges.disconnect(self.connectBeforeCommitChanges)
        except Exception:
            pass

        try:
            layer.nameChanged.connect(self.connectNameChanged)
        except Exception:
            pass
        try:
            layer.beforeCommitChanges.connect(self.connectBeforeCommitChanges)
        except Exception:
            pass

    def connectBeforeCommitChanges(self):
        editLayers = []
        editableLayers = self.iface.editableLayers()
        for editableLayer in editableLayers:
            if not self.searchSpecificLayer(editableLayer.name()):
                continue
            if self.isLayerEditBuffered(editableLayer) is True:
                editLayers.append(editableLayer)
        if len(editLayers) >= 1:
            self.saveEdits(editLayers)

    def searchSpecificLayer(self, layerName):
        try:
            if self.context is None:
                return False

            uri = self.context.getUriDatabaseSqlite()
            if uri is None:
                return False

            if not SQLiteManager.isTableExist(cst.TABLEOFTABLES):
                return False

            if SQLiteManager.selectColumnFromTableWithCondition(cst.TABLEOFTABLES, "layer", layerName) is not None:
                return True

        except Exception as e:
            self.logger.debug("searchSpecificLayer({}): {}".format(layerName, e))

        return False

    def isLayerEditBuffered(self, layer):
        if layer is None:
            return
        layerEditBuffer = layer.editBuffer()
        if layerEditBuffer is not None and (
            len(layerEditBuffer.allAddedOrEditedFeatures()) > 0
            or len(layerEditBuffer.deletedFeatureIds()) > 0
        ):
            return True
        return False

    def saveEdits(self, layers):
        allMessages = []
        for layer in layers:
            messageProgress = "Synchronisation de la couche {}".format(layer.name())
            progress = ProgressBar(len(layers), messageProgress)
            progress.setValue(1)
            allMessages.append(self.saveChangesForOneLayer(layer))
            progress.close()

        dlgInfo = FormInfo()
        dlgInfo.textInfo.setText("<b>Contenu de la transaction</b>")
        dlgInfo.textInfo.setOpenExternalLinks(True)
        if len(allMessages) == 0:
            dlgInfo.textInfo.append("<br/>Vide")

        messageInfo = ''
        print(allMessages)
        for messages in allMessages:
            messageInfo += messages
        print(messageInfo)
        dlgInfo.textInfo.append(messageInfo)
        dlgInfo.exec()

        QApplication.setOverrideCursor(Qt.CursorShape.ArrowCursor)

    def saveChangesForOneLayer(self, layer):
        global commitLayerResult
        ta = "Transaction abandonnée"
        try:
            if layer is None:
                raise Exception("Couche inexistante dans le projet. {}".format(ta))

            if not self.__doConnexion():
                raise Exception("Problème de connexion. {}".format(ta))

            layersTableOfTables = SQLiteManager.selectColumnFromTable(cst.TABLEOFTABLES, 'layer')
            bRes = False
            for layerTableOfTables in layersTableOfTables:
                if layer.name() in layerTableOfTables[0]:
                    bRes = True
                    break

            if not bRes:
                raise Exception(
                    "La couche {} n'est pas présente dans la table des tables de la base SQLite. {}".format(
                        layer.name(), ta
                    )
                )

            editBuffer = layer.editBuffer()
            if not editBuffer:
                raise Exception("Pas de mises à jour enregistrées sur la couche {}. {}".format(layer.name(), ta))

            wfsPost = WfsPost(
                self.context,
                layer,
                RipartHelper.load_CalqueFiltrage(self.context.projectDir).text
            )

            bNormalWfsPost = False
            commitLayerResults = wfsPost.commitLayer(layer.name(), editBuffer, bNormalWfsPost)
            messages = ''

            for commitLayerResult in commitLayerResults:
                messages += "{0}<br/>".format(commitLayerResult['report'])
                if commitLayerResult['status'] == "FAILED":
                    layer.destroyEditCommand()
                else:
                    editBuffer.rollBack()

            self.libelle_transaction = wfsPost.libelle_transaction
            self.getlibelletransaction()

        except Exception as e:
            messages = '<br/><font color="red"><b>{0}</b> : {1}</font>'.format(layer.name(), e)
            QApplication.setOverrideCursor(Qt.CursorShape.ArrowCursor)

        return messages

    def connectNameChanged(self):
        activeLayer = self.iface.activeLayer()
        if activeLayer is None:
            return
        if not self.searchSpecificLayer(activeLayer.name()):
            QMessageBox.warning(
                self.iface.mainWindow(),
                cst.IGNESPACECO,
                "Action interdite ! Veuillez renommer la couche de son nom initial."
            )
        return

    def tr(self, message):
        return QCoreApplication.translate('RipartPlugin', message)

    def add_action(
        self,
        icon_path,
        text,
        callback,
        enabled_flag=True,
        add_to_menu=True,
        add_to_toolbar=True,
        status_tip=None,
        whats_this=None,
        parent=None
        ):
        
        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip is not None:
            action.setStatusTip(status_tip)

        if whats_this is not None:
            action.setWhatsThis(whats_this)

        if add_to_toolbar:
            self.toolbar.addAction(action)

        if add_to_menu:
            self.iface.addPluginToMenu(self.menu, action)

        self.actions.append(action)
        return action

    def initGui(self):
        icon_path = ':/plugins/RipartPlugin/images/connect.png'
        self.add_action(
            icon_path,
            text=self.tr(u'Se connecter a l\'Espace Collaboratif'),
            callback=self.runConnexion,
            status_tip=self.tr(u'Se connecter a l\'Espace Collaboratif'),
            parent=self.iface.mainWindow()
        )

        icon_path = ':/plugins/RipartPlugin/images/update.png'
        self.add_action(
            icon_path,
            text=self.tr(u'Télécharger les signalements'),
            callback=self.downloadReports,
            status_tip=self.tr(u'Télécharger les signalements'),
            parent=self.iface.mainWindow()
        )

        icon_path = ':/plugins/RipartPlugin/images/viewRem.png'
        self.add_action(
            icon_path,
            text=self.tr(u'Voir le signalement'),
            callback=self.viewReport,
            status_tip=self.tr(u'Voir le signalement'),
            parent=self.iface.mainWindow()
        )

        icon_path = ':/plugins/RipartPlugin/images/answer.png'
        self.add_action(
            icon_path,
            text=self.tr(u'Répondre à un signalement'),
            callback=self.answerToReport,
            status_tip=self.tr(u'Répondre à un signalement'),
            parent=self.iface.mainWindow()
        )

        icon_path = ':/plugins/RipartPlugin/images/create.png'
        self.add_action(
            icon_path,
            text=self.tr(u'Créer un nouveau signalement'),
            callback=self.createReport,
            status_tip=self.tr(u'Créer un nouveau signalement'),
            parent=self.iface.mainWindow()
        )

        icon_path = ':/plugins/RipartPlugin/images/cleaning.png'
        self.add_action(
            icon_path,
            text=self.tr(u'Supprimer les signalements de la carte en cours'),
            callback=self.removeReports,
            status_tip=self.tr(u'Supprimer les signalements de la carte en cours'),
            parent=self.iface.mainWindow()
        )

        icon_path = ':/plugins/RipartPlugin/images/magicwand.png'
        self.add_action(
            icon_path,
            text=self.tr(u'Voir les objets associés'),
            callback=self.magicwand,
            status_tip=self.tr(u'Voir les objets associés'),
            parent=self.iface.mainWindow()
        )

        icon_path = ':/plugins/RipartPlugin/images/charger.png'
        self.add_action(
            icon_path,
            text=self.tr(u'Charger les couches de mon groupe'),
            callback=self.loadGuichet,
            status_tip=self.tr(u'Charger les couches de mon groupe'),
            parent=self.iface.mainWindow()
        )

        icon_path = ':/plugins/RipartPlugin/images/synchroniser.png'
        self.add_action(
            icon_path,
            text=self.tr(u'Mettre à jour les couches Espace collaboratif'),
            callback=self.synchronizeData,
            status_tip=self.tr(u'Mettre à jour les couches Espace collaboratif'),
            parent=self.iface.mainWindow()
        )

        self.config.triggered.connect(self.configurePref)
        self.config.setStatusTip(self.tr(u"Ouvre la fenêtre de configuration du plugin."))

        self.about.triggered.connect(self.ripAbout)
        self.help.triggered.connect(self.showHelp)
        self.log.triggered.connect(self.showLog)

        self.helpMenu = QMenu("Aide")
        self.helpMenu.addAction(self.config)
        self.helpMenu.addAction(self.help)
        self.helpMenu.addAction(self.log)
        self.helpMenu.addAction(self.about)

        self.toolButton2 = QToolButton()
        self.toolButton2.setMenu(self.helpMenu)
        self.toolButton2.setPopupMode(TOOLBUTTON_POPUP_INSTANT)
        self.toolButton2.setToolButtonStyle(Qt.ToolButtonStyle.ToolButtonTextOnly)
        self.toolButton2.setText("Aide")

        self.toolbar.addWidget(self.toolButton2)

    def _show_deprecation_warning(self):
        """Affiche un bandeau d'avertissement pour les versions 4.3.5 et 4.3.6."""
        try:
            config = configparser.ConfigParser()
            config.read(os.path.join(self.plugin_dir, 'metadata.txt'))
            version = config.get('general', 'version').strip()
            if version in ('4.3.5', '4.3.6'):
                self.iface.messageBar().pushMessage(
                    "IGN Espace Collaboratif",
                    (
                        "Vous utilisez la version {} du plugin. "
                        "Une version 5.0.x sera prochainement disponible "
                        "sur les dépôts officiels QGIS."
                    ).format(version),
                    level=MSG_LEVEL_WARNING,
                    duration=20
                )
        except Exception as e:
            self.logger.warning("_show_deprecation_warning: {}".format(e))

    def test(self):
        layer = self.iface.activeLayer()
        for f in layer.selectedFeatures():
            fields = f.fields()
            for field in fields:
                name = field.name()
                index = fields.indexOf(name)
                ews = layer.editorWidgetSetup(index)
                print("Name:{0}, Type:{1}, Config:{2}".format(name, ews.type(), ews.config()))

    def __doConnexion(self, bAutomaticConnection=False):
        """
        Point d'entrée explicite des actions Ripart.
        Ici, on autorise la préparation du projet.
        """
        if self.context is None:
            self.context = Contexte.getInstance(self, QgsProject)

        if self.context is None:
            return False

        try:
            self.context.setProjectParams()

            # IMPORTANT :
            # n'écrit sur disque qu'au moment où l'utilisateur demande réellement une action Ripart
            if hasattr(self.context, "ensureProjectReady"):
                self.context.ensureProjectReady()
            else:
                # compat de secours si Contexte.py n'a pas encore été patché
                self.context.checkConfigFile()
                self.context.getOrCreateDatabase()
                self.context.copyRipartStyleFiles()

        except Exception as e:
            self.logger.error("__doConnexion / préparation projet: {}".format(e))
            RipartHelper.showMessageBox(
                u"Impossible de préparer les fichiers du projet pour le plugin IGN Espace Collaboratif.\n{}".format(e)
            )
            return False

        if QgsProject.instance().fileName().find(self.context.projectFileName) == -1:
            return self.context.getConnexionRipart()

        if self.context.client is None or self.context.profil is None or bAutomaticConnection:
            return self.context.getConnexionRipart()

        return True

    def runConnexion(self):
        if not self.__doConnexion(True):
            self.logger.debug("cancel")

    def downloadReports(self):
        try:
            if not self.__doConnexion():
                return
            importRipart = ImporterRipart(self.context)
            result = importRipart.doImport()
            if result == 0:
                return

        except NoProfileException as e:
            self.context.iface.messageBar().clearWidgets()
            self.logger.error(format(e))
            self.context.iface.messageBar().pushMessage(
                "Remarque",
                format(e),
                level=MSG_LEVEL_CRITICAL,
                duration=5
            )
            QApplication.setOverrideCursor(Qt.CursorShape.ArrowCursor)

        except Exception as e:
            self.context.iface.messageBar().clearWidgets()
            self.logger.error(format(e))
            self.context.iface.messageBar().pushMessage(
                "Erreur",
                format(e),
                level=MSG_LEVEL_CRITICAL,
                duration=5
            )
            QApplication.setOverrideCursor(Qt.CursorShape.ArrowCursor)

    def viewReport(self):
        try:
            if not self.__doConnexion():
                return
            seeReport = SeeReport(self.context)
            self.SeeReportView = seeReport.do()

        except Exception as e:
            self.logger.error("SeeReport " + format(e))
            self.context.iface.messageBar().pushMessage(
                "Erreur",
                u"lors de la connexion avec l'Espace Collaboratif. Veuillez réessayer.",
                level=MSG_LEVEL_CRITICAL,
                duration=5
            )

    def answerToReport(self):
        try:
            if not self.__doConnexion():
                return
            replyReport = ReplyReport(self.context)
            replyReport.do()
        except Exception as e:
            self.context.iface.messageBar().pushMessage(
                "Erreur",
                "Problème dans la réponse faite au(x) signalement(s) : {0}".format(str(e)),
                level=MSG_LEVEL_CRITICAL,
                duration=5
            )

    def createReport(self):
        try:
            if not self.__doConnexion():
                return
            create = CreerRipart(self.context)
            create.do()
        except Exception as e:
            self.context.iface.messageBar().pushMessage(
                "Erreur",
                u"Un problème est survenu lors de la création du signalement",
                level=MSG_LEVEL_CRITICAL,
                duration=5
            )

    def removeReports(self):
        try:
            if not self.__doConnexion():
                return

            message = u"Êtes-vous sûr de vouloir supprimer les signalements de la carte en cours?"
            reply = QMessageBox.question(
                self.iface.mainWindow(),
                cst.IGNESPACECO,
                message,
                MSGBOX_YES,
                MSGBOX_NO
            )
            if reply == MSGBOX_YES:
                self.context.emptyAllRipartLayers()
            else:
                return

        except Exception as e:
            self.context.iface.messageBar().pushMessage(
                "Erreur",
                u"Un problème est survenu lors de la suppression des signalements",
                level=MSG_LEVEL_CRITICAL,
                duration=5
            )

    def magicwand(self):
        try:
            if not self.__doConnexion():
                return
            magicw = Magicwand(self.context)
            magicw.selectRipartObjects()

        except Exception as e:
            self.logger.error("magicWand " + format(e))

    def loadGuichet(self):
        try:
            print("Chargement des couches du groupe utilisateur")
            if not self.__doConnexion():
                return

            dlgChargerGuichet = FormChargerGuichet(self.context)

            if dlgChargerGuichet.bRejected:
                if len(dlgChargerGuichet.listLayers) == 0:
                    QMessageBox.warning(
                        self.iface.mainWindow(),
                        cst.IGNESPACECO,
                        "Vous n'appartenez à aucun groupe, il n'y a pas de données à charger."
                    )
                return

            elif dlgChargerGuichet.context.profil is not None:
                if len(dlgChargerGuichet.context.profil.infosGeogroups) == 1 and \
                        len(dlgChargerGuichet.context.profil.infosGeogroups[0].layers) == 0:
                    raise Exception(u"Votre groupe n'a pas paramétré sa carte, il n'y a pas de données à charger.")

            dlgChargerGuichet.exec()

        except Exception as e:
            self.logger.error(format(e))
            self.context.iface.messageBar().pushMessage("Remarque", str(e), level=MSG_LEVEL_WARNING, duration=5)
            QApplication.setOverrideCursor(Qt.CursorShape.ArrowCursor)

    def synchronizeData(self):
        endMessage = '<b>Contenu de la synchronisation</b>'
        print("Synchroniser les données de toutes les couches")

        if not self.__doConnexion():
            return

        layersToSynchronize = []

        if not SQLiteManager.isTableExist(cst.TABLEOFTABLES):
            return

        layersTableOfTables = SQLiteManager.selectColumnFromTable(cst.TABLEOFTABLES, 'layer')
        for layer in QgsProject.instance().mapLayers().values():
            for layerTableOfTables in layersTableOfTables:
                if layer.name() in layerTableOfTables[0]:
                    print('synchronizeData couche : {}'.format(layer.name()))
                    layersToSynchronize.append(layer)
                    break

        if len(layersToSynchronize) == 0:
            endMessage += "<br/>Vide\n"
        else:
            listEditBuffers = []
            messageLayers = ""
            for layer in layersToSynchronize:
                layerEditBuffer = layer.editBuffer()
                if layerEditBuffer is not None and (
                    len(layerEditBuffer.allAddedOrEditedFeatures()) > 0
                    or len(layerEditBuffer.deletedFeatureIds()) > 0
                ):
                    listEditBuffers.append(layerEditBuffer)
                    messageLayers += "{0}, ".format(layer.name())

            if len(listEditBuffers) > 0:
                if len(listEditBuffers) == 1:
                    startMessage = u"La couche {0} contient".format(messageLayers[0:len(messageLayers) - 2])
                else:
                    startMessage = u"Les couches {0} contiennent".format(messageLayers[0:len(messageLayers) - 2])

                message = (
                    "{0} des modifications non enregistrées. Si vous poursuivez la synchronisation, "
                    "vos modifications seront perdues. \nVoulez-vous continuer ?"
                ).format(startMessage)
                reply = QMessageBox.question(
                    self.iface.mainWindow(),
                    cst.IGNESPACECO,
                    message,
                    MSGBOX_YES,
                    MSGBOX_NO
                )
                if reply == MSGBOX_NO:
                    return
                else:
                    for editBuffer in listEditBuffers:
                        editBuffer.rollBack()

        spatialFilterName = RipartHelper.load_CalqueFiltrage(self.context.projectDir).text
        progress = ProgressBar(len(QgsProject.instance().mapLayers()), cst.UPDATETEXTPROGRESS)
        i = 0

        for layer in layersToSynchronize:
            i += 1
            progress.setValue(i)
            endMessage += "<br/><strong>{0}</strong>".format(layer.name())

            bbox = BBox(self.context)
            parameters = {
                'layerName': layer.name(),
                'bbox': bbox.getFromLayer(spatialFilterName),
                'sridProject': cst.EPSGCRS
            }

            result = SQLiteManager.selectRowsInTableOfTables(layer.name())
            if result is not None:
                for r in result:
                    parameters['databasename'] = layer.databasename = r[4]
                    layer.isStandard = r[3]
                    parameters['isStandard'] = r[3]
                    parameters['sridLayer'] = r[5]
                    layer.idNameForDatabase = r[2]
                    parameters['geometryName'] = r[6]
                    parameters['is3D'] = r[7]
                    layer.geometryTypeForDatabase = r[8]

            bDetruit = True
            if layer.isStandard:
                bDetruit = False
                SQLiteManager.emptyTable(layer.name())
                SQLiteManager.vacuumDatabase()
                layer.triggerRepaint()

            parameters['detruit'] = bDetruit
            numrec = SQLiteManager.selectNumrecTableOfTables(layer.name())
            parameters['numrec'] = numrec

            wfsGet = WfsGet(self.context, parameters)
            if not layer.isStandard:
                maxNumrec = wfsGet.getMaxNumrec()
                if numrec == maxNumrec:
                    endMessage += "<br/>Pas de mise à jour\n\n"
                    continue

            maxNumRecMessage = wfsGet.gcms_get()
            SQLiteManager.updateNumrecTableOfTables(layer.name(), maxNumRecMessage[0])
            SQLiteManager.vacuumDatabase()
            endMessage += "<br/>{0}\n".format(maxNumRecMessage[1])

        progress.close()

        dlgInfo = FormInfo()
        dlgInfo.textInfo.setText(endMessage)
        dlgInfo.exec()

    def configurePref(self):
        """
        Lance la fenêtre de configuration des préférences.
        Ici, on prépare explicitement le projet car la config travaille sur le XML projet.
        """
        try:
            self.context = Contexte.getInstance(self, QgsProject)
            if self.context is None:
                return

            self.context.setProjectParams()

            if hasattr(self.context, "ensureProjectReady"):
                self.context.ensureProjectReady()
            else:
                self.context.checkConfigFile()
                self.context.getOrCreateDatabase()
                self.context.copyRipartStyleFiles()

            dlgConfigure = FormConfigure(context=self.context)
            dlgConfigure.exec()

        except Exception as e:
            self.logger.error(format(e))
            if self.context is not None and self.context.iface is not None:
                self.context.iface.messageBar().pushMessage(
                    "Erreur",
                    u"Un problème est survenu dans le chargement de la configuration." + format(e),
                    level=MSG_LEVEL_CRITICAL,
                    duration=5
                )
            else:
                QMessageBox.critical(
                    self.iface.mainWindow(),
                    cst.IGNESPACECO,
                    u"Un problème est survenu dans le chargement de la configuration.\n{}".format(e)
                )

    def ripAbout(self):
        version = '0.'
        date = '2018'

        file_path = os.path.abspath(os.path.join(
            os.path.dirname(__file__), 'metadata.txt'))

        parser = configparser.ConfigParser()
        parser.optionxform = str
        parser.read(file_path)
        if parser.has_section('general'):
            try:
                version = parser.get('general', 'version')
                date = parser.get('general', 'date')
            except Exception:
                self.logger.error("No version/date in metadata")

        dlgInfo = FormInfo()
        dlgInfo.textInfo.setText(u"<b>Plugin Espace Collaboratif</b>")
        dlgInfo.textInfo.append(
            u"<br/>Plugin intégrant les fonctionnalités de signalement et d'écriture de l'Espace collaboratif."
        )
        dlgInfo.textInfo.append(u"<br/>Version : " + version)
        dlgInfo.textInfo.append(u"\u00A9 IGN - " + date)
        dlgInfo.exec()

    def showHelp(self):
        file_path = os.path.abspath(
            os.path.join(os.path.dirname(__file__), "files", RipartHelper.ripart_help_file)
        )
        RipartHelper.open_file(file_path)

    def showLog(self):
        logpath = self.ripartLogger.getLogpath()
        if logpath is not None:
            RipartHelper.open_file(logpath)