# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ConflictsView_base.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ConflictsView(object):
    def setupUi(self, ConflictsView):
        ConflictsView.setObjectName("ConflictsView")
        ConflictsView.resize(1026, 606)
        self.label_type_conflict = QtWidgets.QLabel(ConflictsView)
        self.label_type_conflict.setGeometry(QtCore.QRect(20, 20, 171, 16))
        self.label_type_conflict.setObjectName("label_type_conflict")
        self.label_layer_name = QtWidgets.QLabel(ConflictsView)
        self.label_layer_name.setGeometry(QtCore.QRect(20, 60, 141, 16))
        self.label_layer_name.setObjectName("label_layer_name")
        self.label_context_type_conflict = QtWidgets.QLabel(ConflictsView)
        self.label_context_type_conflict.setGeometry(QtCore.QRect(290, 10, 711, 31))
        self.label_context_type_conflict.setObjectName("label_context_type_conflict")
        self.tableWidget_attributes = QtWidgets.QTableWidget(ConflictsView)
        self.tableWidget_attributes.setGeometry(QtCore.QRect(20, 100, 981, 481))
        self.tableWidget_attributes.setColumnCount(4)
        self.tableWidget_attributes.setObjectName("tableWidget_attributes")
        self.tableWidget_attributes.setRowCount(0)
        self.pushButton_conflict_create = QtWidgets.QPushButton(ConflictsView)
        self.pushButton_conflict_create.setGeometry(QtCore.QRect(510, 50, 40, 40))
        self.pushButton_conflict_create.setToolTip("")
        self.pushButton_conflict_create.setObjectName("pushButton_conflict_create")
        self.pushButton_conflict_previous = QtWidgets.QPushButton(ConflictsView)
        self.pushButton_conflict_previous.setGeometry(QtCore.QRect(560, 50, 40, 40))
        self.pushButton_conflict_previous.setObjectName("pushButton_conflict_previous")
        self.pushButton_conflict_next = QtWidgets.QPushButton(ConflictsView)
        self.pushButton_conflict_next.setGeometry(QtCore.QRect(610, 50, 40, 40))
        self.pushButton_conflict_next.setObjectName("pushButton_conflict_next")
        self.pushButton_conflict_see_all_fields = QtWidgets.QPushButton(ConflictsView)
        self.pushButton_conflict_see_all_fields.setGeometry(QtCore.QRect(660, 50, 40, 40))
        self.pushButton_conflict_see_all_fields.setObjectName("pushButton_conflict_see_all_fields")
        self.pushButton_conflict_reload = QtWidgets.QPushButton(ConflictsView)
        self.pushButton_conflict_reload.setGeometry(QtCore.QRect(710, 50, 40, 40))
        self.pushButton_conflict_reload.setObjectName("pushButton_conflict_reload")
        self.pushButton_conflict_create_2 = QtWidgets.QPushButton(ConflictsView)
        self.pushButton_conflict_create_2.setGeometry(QtCore.QRect(760, 50, 40, 40))
        self.pushButton_conflict_create_2.setObjectName("pushButton_conflict_create_2")
        self.pushButton_conflict_delete = QtWidgets.QPushButton(ConflictsView)
        self.pushButton_conflict_delete.setGeometry(QtCore.QRect(810, 50, 40, 40))
        self.pushButton_conflict_delete.setObjectName("pushButton_conflict_delete")
        self.pushButton_conflict_validate = QtWidgets.QPushButton(ConflictsView)
        self.pushButton_conflict_validate.setGeometry(QtCore.QRect(860, 50, 40, 40))
        self.pushButton_conflict_validate.setObjectName("pushButton_conflict_validate")
        self.pushButton_conflict_validate_all = QtWidgets.QPushButton(ConflictsView)
        self.pushButton_conflict_validate_all.setGeometry(QtCore.QRect(910, 50, 40, 40))
        self.pushButton_conflict_validate_all.setObjectName("pushButton_conflict_validate_all")
        self.pushButton_conflict_undo = QtWidgets.QPushButton(ConflictsView)
        self.pushButton_conflict_undo.setGeometry(QtCore.QRect(960, 50, 40, 40))
        self.pushButton_conflict_undo.setObjectName("pushButton_conflict_undo")

        self.retranslateUi(ConflictsView)
        QtCore.QMetaObject.connectSlotsByName(ConflictsView)

    def retranslateUi(self, ConflictsView):
        _translate = QtCore.QCoreApplication.translate
        ConflictsView.setWindowTitle(_translate("ConflictsView", "Gestion des conflits"))
        self.label_type_conflict.setText(_translate("ConflictsView", "Type de conflit"))
        self.label_layer_name.setText(_translate("ConflictsView", "Nom de la couche"))
        self.label_context_type_conflict.setText(_translate("ConflictsView", "Le contexte du type de conflit"))
        self.pushButton_conflict_create.setText(_translate("ConflictsView", "Report"))
        self.pushButton_conflict_previous.setText(_translate("ConflictsView", "Prev."))
        self.pushButton_conflict_next.setText(_translate("ConflictsView", "Next"))
        self.pushButton_conflict_see_all_fields.setText(_translate("ConflictsView", "See"))
        self.pushButton_conflict_reload.setText(_translate("ConflictsView", "reload"))
        self.pushButton_conflict_create_2.setText(_translate("ConflictsView", "create"))
        self.pushButton_conflict_delete.setText(_translate("ConflictsView", "Delete"))
        self.pushButton_conflict_validate.setText(_translate("ConflictsView", "Val"))
        self.pushButton_conflict_validate_all.setText(_translate("ConflictsView", "Val all"))
        self.pushButton_conflict_undo.setText(_translate("ConflictsView", "Undo"))
