# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'FormConfigure_base.ui'
##
## Created by: Qt User Interface Compiler version 6.10.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from .qt_compat import (
    QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt,
    QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform,
    QAbstractButton, QAbstractItemView, QApplication, QCalendarWidget,
    QCheckBox, QDialog, QDialogButtonBox, QGroupBox,
    QHeaderView, QLabel, QLineEdit, QSizePolicy,
    QSpinBox, QTreeWidget, QTreeWidgetItem, QWidget,
)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        if not Dialog.objectName():
            Dialog.setObjectName(u"Dialog")
        Dialog.resize(861, 693)
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Preferred, QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        font = QFont()
        font.setPointSize(10)
        Dialog.setFont(font)
        icon = QIcon()
        icon.addFile(u":/plugins/RipartPlugin/images/ign.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        Dialog.setWindowIcon(icon)
        Dialog.setModal(True)
        self.buttonBox = QDialogButtonBox(Dialog)
        self.buttonBox.setObjectName(u"buttonBox")
        self.buttonBox.setGeometry(QRect(0, 650, 861, 32))
        self.buttonBox.setOrientation(Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QDialogButtonBox.StandardButton.Cancel|QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setCenterButtons(True)
        self.groupBox = QGroupBox(Dialog)
        self.groupBox.setObjectName(u"groupBox")
        self.groupBox.setGeometry(QRect(20, 10, 821, 191))
        font1 = QFont()
        font1.setPointSize(10)
        font1.setBold(True)
        self.groupBox.setFont(font1)
        self.lineEditUrl = QLineEdit(self.groupBox)
        self.lineEditUrl.setObjectName(u"lineEditUrl")
        self.lineEditUrl.setGeometry(QRect(280, 30, 531, 22))
        self.lineEditUrl.setMinimumSize(QSize(2, 0))
        font2 = QFont()
        font2.setPointSize(10)
        font2.setBold(False)
        self.lineEditUrl.setFont(font2)
        self.lineEditUrl.setFrame(True)
        self.lblUrl = QLabel(self.groupBox)
        self.lblUrl.setObjectName(u"lblUrl")
        self.lblUrl.setGeometry(QRect(10, 30, 221, 22))
        self.lblUrl.setFont(font2)
        self.lineEditLogin = QLineEdit(self.groupBox)
        self.lineEditLogin.setObjectName(u"lineEditLogin")
        self.lineEditLogin.setEnabled(False)
        self.lineEditLogin.setGeometry(QRect(280, 60, 531, 22))
        self.lineEditLogin.setFont(font2)
        self.lineEditGroupeActif = QLineEdit(self.groupBox)
        self.lineEditGroupeActif.setObjectName(u"lineEditGroupeActif")
        self.lineEditGroupeActif.setEnabled(False)
        self.lineEditGroupeActif.setGeometry(QRect(280, 90, 531, 21))
        self.lineEditGroupeActif.setMinimumSize(QSize(2, 0))
        self.lineEditGroupeActif.setFont(font2)
        self.lineEditGroupeActif.setFrame(True)
        self.lineEditGroupeActif.setReadOnly(True)
        self.lblGroupeActif = QLabel(self.groupBox)
        self.lblGroupeActif.setObjectName(u"lblGroupeActif")
        self.lblGroupeActif.setGeometry(QRect(10, 90, 121, 27))
        self.lblGroupeActif.setFont(font2)
        self.lineEditWorkArea = QLineEdit(self.groupBox)
        self.lineEditWorkArea.setObjectName(u"lineEditWorkArea")
        self.lineEditWorkArea.setEnabled(False)
        self.lineEditWorkArea.setGeometry(QRect(280, 120, 531, 22))
        self.lineEditWorkArea.setMinimumSize(QSize(2, 0))
        self.lineEditWorkArea.setFont(font2)
        self.lineEditWorkArea.setFrame(True)
        self.lineEditWorkArea.setReadOnly(True)
        self.lblWorkArea = QLabel(self.groupBox)
        self.lblWorkArea.setObjectName(u"lblWorkArea")
        self.lblWorkArea.setGeometry(QRect(10, 120, 121, 22))
        self.lblWorkArea.setFont(font2)
        self.lineEditProxy = QLineEdit(self.groupBox)
        self.lineEditProxy.setObjectName(u"lineEditProxy")
        self.lineEditProxy.setGeometry(QRect(280, 150, 531, 22))
        self.lineEditProxy.setMinimumSize(QSize(2, 0))
        self.lineEditProxy.setFont(font2)
        self.lineEditProxy.setFrame(True)
        self.lblLogin = QLabel(self.groupBox)
        self.lblLogin.setObjectName(u"lblLogin")
        self.lblLogin.setGeometry(QRect(10, 60, 121, 27))
        self.lblLogin.setFont(font2)
        self.checkBoxProxy = QCheckBox(Dialog)
        self.checkBoxProxy.setObjectName(u"checkBoxProxy")
        self.checkBoxProxy.setGeometry(QRect(30, 160, 71, 20))
        sizePolicy1 = QSizePolicy(QSizePolicy.Policy.Maximum, QSizePolicy.Policy.Fixed)
        sizePolicy1.setHorizontalStretch(0)
        sizePolicy1.setVerticalStretch(0)
        sizePolicy1.setHeightForWidth(self.checkBoxProxy.sizePolicy().hasHeightForWidth())
        self.checkBoxProxy.setSizePolicy(sizePolicy1)
        self.checkBoxProxy.setMinimumSize(QSize(0, 0))
        self.checkBoxProxy.setFont(font2)
        self.checkBoxProxy.setLayoutDirection(Qt.LayoutDirection.LeftToRight)
        self.checkBoxProxy.setAutoFillBackground(False)
        self.groupBox_2 = QGroupBox(Dialog)
        self.groupBox_2.setObjectName(u"groupBox_2")
        self.groupBox_2.setGeometry(QRect(20, 220, 821, 421))
        self.groupBox_2.setFont(font1)
        self.checkBoxDate = QCheckBox(self.groupBox_2)
        self.checkBoxDate.setObjectName(u"checkBoxDate")
        self.checkBoxDate.setGeometry(QRect(10, 30, 161, 20))
        sizePolicy1.setHeightForWidth(self.checkBoxDate.sizePolicy().hasHeightForWidth())
        self.checkBoxDate.setSizePolicy(sizePolicy1)
        self.checkBoxDate.setMinimumSize(QSize(0, 0))
        self.checkBoxDate.setFont(font2)
        self.checkBoxDate.setLayoutDirection(Qt.LayoutDirection.LeftToRight)
        self.checkBoxDate.setAutoFillBackground(False)
        self.treeWidget = QTreeWidget(self.groupBox_2)
        __qtreewidgetitem = QTreeWidgetItem()
        __qtreewidgetitem.setText(0, u"1");
        self.treeWidget.setHeaderItem(__qtreewidgetitem)
        self.treeWidget.setObjectName(u"treeWidget")
        self.treeWidget.setGeometry(QRect(10, 251, 801, 161))
        self.treeWidget.setLineWidth(100)
        self.treeWidget.setAlternatingRowColors(True)
        self.treeWidget.setSelectionMode(QAbstractItemView.SelectionMode.MultiSelection)
        self.treeWidget.setColumnCount(1)
        self.treeWidget.header().setVisible(False)
        self.checkBoxAttributs = QCheckBox(self.groupBox_2)
        self.checkBoxAttributs.setObjectName(u"checkBoxAttributs")
        self.checkBoxAttributs.setGeometry(QRect(10, 210, 661, 36))
        sizePolicy1.setHeightForWidth(self.checkBoxAttributs.sizePolicy().hasHeightForWidth())
        self.checkBoxAttributs.setSizePolicy(sizePolicy1)
        self.checkBoxAttributs.setMinimumSize(QSize(0, 0))
        self.checkBoxAttributs.setFont(font2)
        self.checkBoxAttributs.setLayoutDirection(Qt.LayoutDirection.LeftToRight)
        self.checkBoxAttributs.setAutoFillBackground(False)
        self.calendarWidget = QCalendarWidget(self.groupBox_2)
        self.calendarWidget.setObjectName(u"calendarWidget")
        self.calendarWidget.setGeometry(QRect(280, 30, 291, 181))
        font3 = QFont()
        font3.setPointSize(8)
        font3.setBold(False)
        self.calendarWidget.setFont(font3)
        self.calendarWidget.setHorizontalHeaderFormat(QCalendarWidget.HorizontalHeaderFormat.ShortDayNames)
        self.calendarWidget.setVerticalHeaderFormat(QCalendarWidget.VerticalHeaderFormat.NoVerticalHeader)
        self.calendarWidget.setNavigationBarVisible(True)
        self.spinBox = QSpinBox(self.groupBox_2)
        self.spinBox.setObjectName(u"spinBox")
        self.spinBox.setGeometry(QRect(590, 90, 111, 22))
        self.spinBox.setFont(font2)
        self.spinBox.setMaximum(2147483647)
        self.label_2 = QLabel(self.groupBox_2)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(710, 80, 61, 41))
        self.label_2.setFont(font2)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)

        QMetaObject.connectSlotsByName(Dialog)
    # setupUi

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QCoreApplication.translate("Dialog", u"Configuration du plugin Espace Collaboratif", None))
        self.groupBox.setTitle(QCoreApplication.translate("Dialog", u"G\u00e9n\u00e9ral", None))
        self.lblUrl.setText(QCoreApplication.translate("Dialog", u"Site web Espace Collaboratif", None))
        self.lblGroupeActif.setText(QCoreApplication.translate("Dialog", u"Groupe actif", None))
        self.lblWorkArea.setText(QCoreApplication.translate("Dialog", u"Zone de travail", None))
        self.lblLogin.setText(QCoreApplication.translate("Dialog", u"Login actif", None))
        self.checkBoxProxy.setText(QCoreApplication.translate("Dialog", u"Proxy", None))
        self.groupBox_2.setTitle(QCoreApplication.translate("Dialog", u"Signalements", None))
        self.checkBoxDate.setText(QCoreApplication.translate("Dialog", u"Date d'extraction", None))
        self.checkBoxAttributs.setText(QCoreApplication.translate("Dialog", u"Couches sources et champs \u00e0 mettre en attribut pour les nouveaux croquis", None))
        self.label_2.setText(QCoreApplication.translate("Dialog", u"jours", None))
    # retranslateUi

