# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SeeReportView_base.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SeeReportView(object):
    def setupUi(self, SeeReportView):
        SeeReportView.setObjectName("SeeReportView")
        SeeReportView.resize(651, 580)
        font = QtGui.QFont()
        font.setPointSize(1)
        SeeReportView.setFont(font)
        SeeReportView.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lbl_generalInformation = QtWidgets.QLabel(SeeReportView)
        self.lbl_generalInformation.setGeometry(QtCore.QRect(10, 50, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_generalInformation.setFont(font)
        self.lbl_generalInformation.setObjectName("lbl_generalInformation")
        self.lbl_contentNumberReport = QtWidgets.QLabel(SeeReportView)
        self.lbl_contentNumberReport.setGeometry(QtCore.QRect(110, 10, 331, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_contentNumberReport.setFont(font)
        self.lbl_contentNumberReport.setText("")
        self.lbl_contentNumberReport.setObjectName("lbl_contentNumberReport")
        self.lbl_themes = QtWidgets.QLabel(SeeReportView)
        self.lbl_themes.setGeometry(QtCore.QRect(380, 50, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_themes.setFont(font)
        self.lbl_themes.setObjectName("lbl_themes")
        self.lbl_description = QtWidgets.QLabel(SeeReportView)
        self.lbl_description.setGeometry(QtCore.QRect(10, 240, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_description.setFont(font)
        self.lbl_description.setObjectName("lbl_description")
        self.lbl_documents = QtWidgets.QLabel(SeeReportView)
        self.lbl_documents.setGeometry(QtCore.QRect(10, 370, 161, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_documents.setFont(font)
        self.lbl_documents.setObjectName("lbl_documents")
        self.lbl_responses = QtWidgets.QLabel(SeeReportView)
        self.lbl_responses.setGeometry(QtCore.QRect(10, 450, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_responses.setFont(font)
        self.lbl_responses.setObjectName("lbl_responses")
        self.lbl_displayGeneralInformation = QtWidgets.QLabel(SeeReportView)
        self.lbl_displayGeneralInformation.setGeometry(QtCore.QRect(10, 90, 351, 141))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.lbl_displayGeneralInformation.setFont(font)
        self.lbl_displayGeneralInformation.setText("")
        self.lbl_displayGeneralInformation.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.lbl_displayGeneralInformation.setWordWrap(True)
        self.lbl_displayGeneralInformation.setObjectName("lbl_displayGeneralInformation")
        self.lbl_displayDocuments = QtWidgets.QLabel(SeeReportView)
        self.lbl_displayDocuments.setGeometry(QtCore.QRect(10, 390, 631, 51))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.lbl_displayDocuments.setFont(font)
        self.lbl_displayDocuments.setText("")
        self.lbl_displayDocuments.setTextFormat(QtCore.Qt.RichText)
        self.lbl_displayDocuments.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.lbl_displayDocuments.setWordWrap(False)
        self.lbl_displayDocuments.setOpenExternalLinks(True)
        self.lbl_displayDocuments.setTextInteractionFlags(QtCore.Qt.TextBrowserInteraction)
        self.lbl_displayDocuments.setObjectName("lbl_displayDocuments")
        self.lbl_displayDescription = QtWidgets.QLabel(SeeReportView)
        self.lbl_displayDescription.setGeometry(QtCore.QRect(10, 270, 631, 91))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.lbl_displayDescription.setFont(font)
        self.lbl_displayDescription.setText("")
        self.lbl_displayDescription.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.lbl_displayDescription.setWordWrap(True)
        self.lbl_displayDescription.setObjectName("lbl_displayDescription")
        self.pte_displayThemes = QtWidgets.QPlainTextEdit(SeeReportView)
        self.pte_displayThemes.setGeometry(QtCore.QRect(370, 80, 271, 161))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.pte_displayThemes.setFont(font)
        self.pte_displayThemes.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.pte_displayThemes.setLineWrapMode(QtWidgets.QPlainTextEdit.NoWrap)
        self.pte_displayThemes.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.pte_displayThemes.setObjectName("pte_displayThemes")
        self.pte_displayResponses = QtWidgets.QPlainTextEdit(SeeReportView)
        self.pte_displayResponses.setGeometry(QtCore.QRect(10, 480, 631, 91))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.pte_displayResponses.setFont(font)
        self.pte_displayResponses.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.pte_displayResponses.setLineWrapMode(QtWidgets.QPlainTextEdit.NoWrap)
        self.pte_displayResponses.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.pte_displayResponses.setObjectName("pte_displayResponses")

        self.retranslateUi(SeeReportView)
        QtCore.QMetaObject.connectSlotsByName(SeeReportView)

    def retranslateUi(self, SeeReportView):
        _translate = QtCore.QCoreApplication.translate
        SeeReportView.setWindowTitle(_translate("SeeReportView", "Voir un signalement"))
        self.lbl_generalInformation.setText(_translate("SeeReportView", "Informations générales"))
        self.lbl_themes.setText(_translate("SeeReportView", "Thèmes"))
        self.lbl_description.setText(_translate("SeeReportView", "Description"))
        self.lbl_documents.setText(_translate("SeeReportView", "Document(s) joint(s)"))
        self.lbl_responses.setText(_translate("SeeReportView", "Réponses"))
